// Code generated by protoc-gen-go. DO NOT EDIT.
// source: info.proto

package dayan_community_srv_info

import (
	fmt "fmt"
	idl "github.com/dy-dayan/community-srv-info/idl"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommunityCommon struct {
	Name                 string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Province             string    `protobuf:"bytes,2,opt,name=Province,proto3" json:"Province,omitempty"`
	City                 string    `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	Region               string    `protobuf:"bytes,4,opt,name=Region,proto3" json:"Region,omitempty"`
	Street               string    `protobuf:"bytes,5,opt,name=Street,proto3" json:"Street,omitempty"`
	CouncilID            int64     `protobuf:"varint,6,opt,name=CouncilID,proto3" json:"CouncilID,omitempty"`
	OrgID                int64     `protobuf:"varint,7,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	HouseCount           int32     `protobuf:"varint,8,opt,name=HouseCount,proto3" json:"HouseCount,omitempty"`
	CheckInCount         int32     `protobuf:"varint,9,opt,name=CheckInCount,proto3" json:"CheckInCount,omitempty"`
	BuildingArea         int32     `protobuf:"varint,10,opt,name=BuildingArea,proto3" json:"BuildingArea,omitempty"`
	GreeningArea         int32     `protobuf:"varint,11,opt,name=GreeningArea,proto3" json:"GreeningArea,omitempty"`
	Loc                  []float32 `protobuf:"fixed32,12,rep,packed,name=Loc,proto3" json:"Loc,omitempty"`
	State                int32     `protobuf:"varint,13,opt,name=State,proto3" json:"State,omitempty"`
	OperatorID           int64     `protobuf:"varint,14,opt,name=OperatorID,proto3" json:"OperatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CommunityCommon) Reset()         { *m = CommunityCommon{} }
func (m *CommunityCommon) String() string { return proto.CompactTextString(m) }
func (*CommunityCommon) ProtoMessage()    {}
func (*CommunityCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{0}
}

func (m *CommunityCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityCommon.Unmarshal(m, b)
}
func (m *CommunityCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityCommon.Marshal(b, m, deterministic)
}
func (m *CommunityCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityCommon.Merge(m, src)
}
func (m *CommunityCommon) XXX_Size() int {
	return xxx_messageInfo_CommunityCommon.Size(m)
}
func (m *CommunityCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityCommon.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityCommon proto.InternalMessageInfo

func (m *CommunityCommon) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommunityCommon) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *CommunityCommon) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CommunityCommon) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *CommunityCommon) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *CommunityCommon) GetCouncilID() int64 {
	if m != nil {
		return m.CouncilID
	}
	return 0
}

func (m *CommunityCommon) GetOrgID() int64 {
	if m != nil {
		return m.OrgID
	}
	return 0
}

func (m *CommunityCommon) GetHouseCount() int32 {
	if m != nil {
		return m.HouseCount
	}
	return 0
}

func (m *CommunityCommon) GetCheckInCount() int32 {
	if m != nil {
		return m.CheckInCount
	}
	return 0
}

func (m *CommunityCommon) GetBuildingArea() int32 {
	if m != nil {
		return m.BuildingArea
	}
	return 0
}

func (m *CommunityCommon) GetGreeningArea() int32 {
	if m != nil {
		return m.GreeningArea
	}
	return 0
}

func (m *CommunityCommon) GetLoc() []float32 {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *CommunityCommon) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *CommunityCommon) GetOperatorID() int64 {
	if m != nil {
		return m.OperatorID
	}
	return 0
}

type AddCommunityReq struct {
	Community            *CommunityCommon `protobuf:"bytes,1,opt,name=Community,proto3" json:"Community,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddCommunityReq) Reset()         { *m = AddCommunityReq{} }
func (m *AddCommunityReq) String() string { return proto.CompactTextString(m) }
func (*AddCommunityReq) ProtoMessage()    {}
func (*AddCommunityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{1}
}

func (m *AddCommunityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommunityReq.Unmarshal(m, b)
}
func (m *AddCommunityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommunityReq.Marshal(b, m, deterministic)
}
func (m *AddCommunityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommunityReq.Merge(m, src)
}
func (m *AddCommunityReq) XXX_Size() int {
	return xxx_messageInfo_AddCommunityReq.Size(m)
}
func (m *AddCommunityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommunityReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommunityReq proto.InternalMessageInfo

func (m *AddCommunityReq) GetCommunity() *CommunityCommon {
	if m != nil {
		return m.Community
	}
	return nil
}

type AddCommunityResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	CommunityID          int64     `protobuf:"varint,2,opt,name=CommunityID,proto3" json:"CommunityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddCommunityResp) Reset()         { *m = AddCommunityResp{} }
func (m *AddCommunityResp) String() string { return proto.CompactTextString(m) }
func (*AddCommunityResp) ProtoMessage()    {}
func (*AddCommunityResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{2}
}

func (m *AddCommunityResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommunityResp.Unmarshal(m, b)
}
func (m *AddCommunityResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommunityResp.Marshal(b, m, deterministic)
}
func (m *AddCommunityResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommunityResp.Merge(m, src)
}
func (m *AddCommunityResp) XXX_Size() int {
	return xxx_messageInfo_AddCommunityResp.Size(m)
}
func (m *AddCommunityResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommunityResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommunityResp proto.InternalMessageInfo

func (m *AddCommunityResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *AddCommunityResp) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

type DelCommunityReq struct {
	CommunityID          int64    `protobuf:"varint,1,opt,name=CommunityID,proto3" json:"CommunityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelCommunityReq) Reset()         { *m = DelCommunityReq{} }
func (m *DelCommunityReq) String() string { return proto.CompactTextString(m) }
func (*DelCommunityReq) ProtoMessage()    {}
func (*DelCommunityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{3}
}

func (m *DelCommunityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCommunityReq.Unmarshal(m, b)
}
func (m *DelCommunityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCommunityReq.Marshal(b, m, deterministic)
}
func (m *DelCommunityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCommunityReq.Merge(m, src)
}
func (m *DelCommunityReq) XXX_Size() int {
	return xxx_messageInfo_DelCommunityReq.Size(m)
}
func (m *DelCommunityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCommunityReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelCommunityReq proto.InternalMessageInfo

func (m *DelCommunityReq) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

type DelCommunityResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DelCommunityResp) Reset()         { *m = DelCommunityResp{} }
func (m *DelCommunityResp) String() string { return proto.CompactTextString(m) }
func (*DelCommunityResp) ProtoMessage()    {}
func (*DelCommunityResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{4}
}

func (m *DelCommunityResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCommunityResp.Unmarshal(m, b)
}
func (m *DelCommunityResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCommunityResp.Marshal(b, m, deterministic)
}
func (m *DelCommunityResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCommunityResp.Merge(m, src)
}
func (m *DelCommunityResp) XXX_Size() int {
	return xxx_messageInfo_DelCommunityResp.Size(m)
}
func (m *DelCommunityResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCommunityResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelCommunityResp proto.InternalMessageInfo

func (m *DelCommunityResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetCommunityReq struct {
	CommunityID          int64    `protobuf:"varint,1,opt,name=CommunityID,proto3" json:"CommunityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommunityReq) Reset()         { *m = GetCommunityReq{} }
func (m *GetCommunityReq) String() string { return proto.CompactTextString(m) }
func (*GetCommunityReq) ProtoMessage()    {}
func (*GetCommunityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{5}
}

func (m *GetCommunityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommunityReq.Unmarshal(m, b)
}
func (m *GetCommunityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommunityReq.Marshal(b, m, deterministic)
}
func (m *GetCommunityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommunityReq.Merge(m, src)
}
func (m *GetCommunityReq) XXX_Size() int {
	return xxx_messageInfo_GetCommunityReq.Size(m)
}
func (m *GetCommunityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommunityReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommunityReq proto.InternalMessageInfo

func (m *GetCommunityReq) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

type GetCommunityResp struct {
	BaseResp             *idl.Resp        `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	Community            *CommunityCommon `protobuf:"bytes,2,opt,name=Community,proto3" json:"Community,omitempty"`
	CreatedAt            int64            `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            int64            `protobuf:"varint,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetCommunityResp) Reset()         { *m = GetCommunityResp{} }
func (m *GetCommunityResp) String() string { return proto.CompactTextString(m) }
func (*GetCommunityResp) ProtoMessage()    {}
func (*GetCommunityResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{6}
}

func (m *GetCommunityResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommunityResp.Unmarshal(m, b)
}
func (m *GetCommunityResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommunityResp.Marshal(b, m, deterministic)
}
func (m *GetCommunityResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommunityResp.Merge(m, src)
}
func (m *GetCommunityResp) XXX_Size() int {
	return xxx_messageInfo_GetCommunityResp.Size(m)
}
func (m *GetCommunityResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommunityResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommunityResp proto.InternalMessageInfo

func (m *GetCommunityResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetCommunityResp) GetCommunity() *CommunityCommon {
	if m != nil {
		return m.Community
	}
	return nil
}

func (m *GetCommunityResp) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GetCommunityResp) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type AssetCommon struct {
	Serial               string   `protobuf:"bytes,1,opt,name=Serial,proto3" json:"Serial,omitempty"`
	Category             int32    `protobuf:"varint,2,opt,name=Category,proto3" json:"Category,omitempty"`
	State                int32    `protobuf:"varint,3,opt,name=State,proto3" json:"State,omitempty"`
	CommunityID          int64    `protobuf:"varint,4,opt,name=CommunityID,proto3" json:"CommunityID,omitempty"`
	Loc                  string   `protobuf:"bytes,5,opt,name=loc,proto3" json:"loc,omitempty"`
	Brand                string   `protobuf:"bytes,6,opt,name=Brand,proto3" json:"Brand,omitempty"`
	Desc                 string   `protobuf:"bytes,7,opt,name=Desc,proto3" json:"Desc,omitempty"`
	OperatorID           int64    `protobuf:"varint,8,opt,name=OperatorID,proto3" json:"OperatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetCommon) Reset()         { *m = AssetCommon{} }
func (m *AssetCommon) String() string { return proto.CompactTextString(m) }
func (*AssetCommon) ProtoMessage()    {}
func (*AssetCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{7}
}

func (m *AssetCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetCommon.Unmarshal(m, b)
}
func (m *AssetCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetCommon.Marshal(b, m, deterministic)
}
func (m *AssetCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetCommon.Merge(m, src)
}
func (m *AssetCommon) XXX_Size() int {
	return xxx_messageInfo_AssetCommon.Size(m)
}
func (m *AssetCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetCommon.DiscardUnknown(m)
}

var xxx_messageInfo_AssetCommon proto.InternalMessageInfo

func (m *AssetCommon) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *AssetCommon) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *AssetCommon) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *AssetCommon) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

func (m *AssetCommon) GetLoc() string {
	if m != nil {
		return m.Loc
	}
	return ""
}

func (m *AssetCommon) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *AssetCommon) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *AssetCommon) GetOperatorID() int64 {
	if m != nil {
		return m.OperatorID
	}
	return 0
}

type AddAssetReq struct {
	Asset                *AssetCommon `protobuf:"bytes,1,opt,name=Asset,proto3" json:"Asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddAssetReq) Reset()         { *m = AddAssetReq{} }
func (m *AddAssetReq) String() string { return proto.CompactTextString(m) }
func (*AddAssetReq) ProtoMessage()    {}
func (*AddAssetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{8}
}

func (m *AddAssetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAssetReq.Unmarshal(m, b)
}
func (m *AddAssetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAssetReq.Marshal(b, m, deterministic)
}
func (m *AddAssetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAssetReq.Merge(m, src)
}
func (m *AddAssetReq) XXX_Size() int {
	return xxx_messageInfo_AddAssetReq.Size(m)
}
func (m *AddAssetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAssetReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddAssetReq proto.InternalMessageInfo

func (m *AddAssetReq) GetAsset() *AssetCommon {
	if m != nil {
		return m.Asset
	}
	return nil
}

type AddAssetResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	AssetID              int64     `protobuf:"varint,2,opt,name=AssetID,proto3" json:"AssetID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddAssetResp) Reset()         { *m = AddAssetResp{} }
func (m *AddAssetResp) String() string { return proto.CompactTextString(m) }
func (*AddAssetResp) ProtoMessage()    {}
func (*AddAssetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{9}
}

func (m *AddAssetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAssetResp.Unmarshal(m, b)
}
func (m *AddAssetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAssetResp.Marshal(b, m, deterministic)
}
func (m *AddAssetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAssetResp.Merge(m, src)
}
func (m *AddAssetResp) XXX_Size() int {
	return xxx_messageInfo_AddAssetResp.Size(m)
}
func (m *AddAssetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAssetResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddAssetResp proto.InternalMessageInfo

func (m *AddAssetResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *AddAssetResp) GetAssetID() int64 {
	if m != nil {
		return m.AssetID
	}
	return 0
}

type DelAssetReq struct {
	AssetID              int64    `protobuf:"varint,1,opt,name=AssetID,proto3" json:"AssetID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelAssetReq) Reset()         { *m = DelAssetReq{} }
func (m *DelAssetReq) String() string { return proto.CompactTextString(m) }
func (*DelAssetReq) ProtoMessage()    {}
func (*DelAssetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{10}
}

func (m *DelAssetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelAssetReq.Unmarshal(m, b)
}
func (m *DelAssetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelAssetReq.Marshal(b, m, deterministic)
}
func (m *DelAssetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelAssetReq.Merge(m, src)
}
func (m *DelAssetReq) XXX_Size() int {
	return xxx_messageInfo_DelAssetReq.Size(m)
}
func (m *DelAssetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelAssetReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelAssetReq proto.InternalMessageInfo

func (m *DelAssetReq) GetAssetID() int64 {
	if m != nil {
		return m.AssetID
	}
	return 0
}

type DelAssetResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DelAssetResp) Reset()         { *m = DelAssetResp{} }
func (m *DelAssetResp) String() string { return proto.CompactTextString(m) }
func (*DelAssetResp) ProtoMessage()    {}
func (*DelAssetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{11}
}

func (m *DelAssetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelAssetResp.Unmarshal(m, b)
}
func (m *DelAssetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelAssetResp.Marshal(b, m, deterministic)
}
func (m *DelAssetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelAssetResp.Merge(m, src)
}
func (m *DelAssetResp) XXX_Size() int {
	return xxx_messageInfo_DelAssetResp.Size(m)
}
func (m *DelAssetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelAssetResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelAssetResp proto.InternalMessageInfo

func (m *DelAssetResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetAssetReq struct {
	AssetID              int64    `protobuf:"varint,1,opt,name=AssetID,proto3" json:"AssetID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAssetReq) Reset()         { *m = GetAssetReq{} }
func (m *GetAssetReq) String() string { return proto.CompactTextString(m) }
func (*GetAssetReq) ProtoMessage()    {}
func (*GetAssetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{12}
}

func (m *GetAssetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetReq.Unmarshal(m, b)
}
func (m *GetAssetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetReq.Marshal(b, m, deterministic)
}
func (m *GetAssetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetReq.Merge(m, src)
}
func (m *GetAssetReq) XXX_Size() int {
	return xxx_messageInfo_GetAssetReq.Size(m)
}
func (m *GetAssetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetReq proto.InternalMessageInfo

func (m *GetAssetReq) GetAssetID() int64 {
	if m != nil {
		return m.AssetID
	}
	return 0
}

type GetAssetResp struct {
	BaseResp             *idl.Resp    `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	Asset                *AssetCommon `protobuf:"bytes,2,opt,name=Asset,proto3" json:"Asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetAssetResp) Reset()         { *m = GetAssetResp{} }
func (m *GetAssetResp) String() string { return proto.CompactTextString(m) }
func (*GetAssetResp) ProtoMessage()    {}
func (*GetAssetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{13}
}

func (m *GetAssetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetResp.Unmarshal(m, b)
}
func (m *GetAssetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetResp.Marshal(b, m, deterministic)
}
func (m *GetAssetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetResp.Merge(m, src)
}
func (m *GetAssetResp) XXX_Size() int {
	return xxx_messageInfo_GetAssetResp.Size(m)
}
func (m *GetAssetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetResp proto.InternalMessageInfo

func (m *GetAssetResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetAssetResp) GetAsset() *AssetCommon {
	if m != nil {
		return m.Asset
	}
	return nil
}

type BuildingCommon struct {
	Name                 string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	CommunityID          int64     `protobuf:"varint,2,opt,name=CommunityID,proto3" json:"CommunityID,omitempty"`
	Period               int32     `protobuf:"varint,3,opt,name=Period,proto3" json:"Period,omitempty"`
	ElevatorID           []int64   `protobuf:"varint,4,rep,packed,name=ElevatorID,proto3" json:"ElevatorID,omitempty"`
	Loc                  []float32 `protobuf:"fixed32,5,rep,packed,name=Loc,proto3" json:"Loc,omitempty"`
	OperatorID           int64     `protobuf:"varint,6,opt,name=OperatorID,proto3" json:"OperatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BuildingCommon) Reset()         { *m = BuildingCommon{} }
func (m *BuildingCommon) String() string { return proto.CompactTextString(m) }
func (*BuildingCommon) ProtoMessage()    {}
func (*BuildingCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{14}
}

func (m *BuildingCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildingCommon.Unmarshal(m, b)
}
func (m *BuildingCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildingCommon.Marshal(b, m, deterministic)
}
func (m *BuildingCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildingCommon.Merge(m, src)
}
func (m *BuildingCommon) XXX_Size() int {
	return xxx_messageInfo_BuildingCommon.Size(m)
}
func (m *BuildingCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildingCommon.DiscardUnknown(m)
}

var xxx_messageInfo_BuildingCommon proto.InternalMessageInfo

func (m *BuildingCommon) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuildingCommon) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

func (m *BuildingCommon) GetPeriod() int32 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *BuildingCommon) GetElevatorID() []int64 {
	if m != nil {
		return m.ElevatorID
	}
	return nil
}

func (m *BuildingCommon) GetLoc() []float32 {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *BuildingCommon) GetOperatorID() int64 {
	if m != nil {
		return m.OperatorID
	}
	return 0
}

type AddBuildingReq struct {
	Building             *BuildingCommon `protobuf:"bytes,1,opt,name=Building,proto3" json:"Building,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddBuildingReq) Reset()         { *m = AddBuildingReq{} }
func (m *AddBuildingReq) String() string { return proto.CompactTextString(m) }
func (*AddBuildingReq) ProtoMessage()    {}
func (*AddBuildingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{15}
}

func (m *AddBuildingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBuildingReq.Unmarshal(m, b)
}
func (m *AddBuildingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBuildingReq.Marshal(b, m, deterministic)
}
func (m *AddBuildingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBuildingReq.Merge(m, src)
}
func (m *AddBuildingReq) XXX_Size() int {
	return xxx_messageInfo_AddBuildingReq.Size(m)
}
func (m *AddBuildingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBuildingReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddBuildingReq proto.InternalMessageInfo

func (m *AddBuildingReq) GetBuilding() *BuildingCommon {
	if m != nil {
		return m.Building
	}
	return nil
}

type AddBuildingResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	ID                   int64     `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddBuildingResp) Reset()         { *m = AddBuildingResp{} }
func (m *AddBuildingResp) String() string { return proto.CompactTextString(m) }
func (*AddBuildingResp) ProtoMessage()    {}
func (*AddBuildingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{16}
}

func (m *AddBuildingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBuildingResp.Unmarshal(m, b)
}
func (m *AddBuildingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBuildingResp.Marshal(b, m, deterministic)
}
func (m *AddBuildingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBuildingResp.Merge(m, src)
}
func (m *AddBuildingResp) XXX_Size() int {
	return xxx_messageInfo_AddBuildingResp.Size(m)
}
func (m *AddBuildingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBuildingResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddBuildingResp proto.InternalMessageInfo

func (m *AddBuildingResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *AddBuildingResp) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DelBuilingReq struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelBuilingReq) Reset()         { *m = DelBuilingReq{} }
func (m *DelBuilingReq) String() string { return proto.CompactTextString(m) }
func (*DelBuilingReq) ProtoMessage()    {}
func (*DelBuilingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{17}
}

func (m *DelBuilingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelBuilingReq.Unmarshal(m, b)
}
func (m *DelBuilingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelBuilingReq.Marshal(b, m, deterministic)
}
func (m *DelBuilingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelBuilingReq.Merge(m, src)
}
func (m *DelBuilingReq) XXX_Size() int {
	return xxx_messageInfo_DelBuilingReq.Size(m)
}
func (m *DelBuilingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelBuilingReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelBuilingReq proto.InternalMessageInfo

func (m *DelBuilingReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DelBuilingResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DelBuilingResp) Reset()         { *m = DelBuilingResp{} }
func (m *DelBuilingResp) String() string { return proto.CompactTextString(m) }
func (*DelBuilingResp) ProtoMessage()    {}
func (*DelBuilingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{18}
}

func (m *DelBuilingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelBuilingResp.Unmarshal(m, b)
}
func (m *DelBuilingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelBuilingResp.Marshal(b, m, deterministic)
}
func (m *DelBuilingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelBuilingResp.Merge(m, src)
}
func (m *DelBuilingResp) XXX_Size() int {
	return xxx_messageInfo_DelBuilingResp.Size(m)
}
func (m *DelBuilingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelBuilingResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelBuilingResp proto.InternalMessageInfo

func (m *DelBuilingResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetBuildingReq struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuildingReq) Reset()         { *m = GetBuildingReq{} }
func (m *GetBuildingReq) String() string { return proto.CompactTextString(m) }
func (*GetBuildingReq) ProtoMessage()    {}
func (*GetBuildingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{19}
}

func (m *GetBuildingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildingReq.Unmarshal(m, b)
}
func (m *GetBuildingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildingReq.Marshal(b, m, deterministic)
}
func (m *GetBuildingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildingReq.Merge(m, src)
}
func (m *GetBuildingReq) XXX_Size() int {
	return xxx_messageInfo_GetBuildingReq.Size(m)
}
func (m *GetBuildingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildingReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildingReq proto.InternalMessageInfo

func (m *GetBuildingReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetBuildingResp struct {
	BaseResp             *idl.Resp       `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	Building             *BuildingCommon `protobuf:"bytes,2,opt,name=Building,proto3" json:"Building,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetBuildingResp) Reset()         { *m = GetBuildingResp{} }
func (m *GetBuildingResp) String() string { return proto.CompactTextString(m) }
func (*GetBuildingResp) ProtoMessage()    {}
func (*GetBuildingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{20}
}

func (m *GetBuildingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildingResp.Unmarshal(m, b)
}
func (m *GetBuildingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildingResp.Marshal(b, m, deterministic)
}
func (m *GetBuildingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildingResp.Merge(m, src)
}
func (m *GetBuildingResp) XXX_Size() int {
	return xxx_messageInfo_GetBuildingResp.Size(m)
}
func (m *GetBuildingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildingResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildingResp proto.InternalMessageInfo

func (m *GetBuildingResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetBuildingResp) GetBuilding() *BuildingCommon {
	if m != nil {
		return m.Building
	}
	return nil
}

type HouseCommon struct {
	BuildingID           int64    `protobuf:"varint,1,opt,name=BuildingID,proto3" json:"BuildingID,omitempty"`
	Unit                 string   `protobuf:"bytes,2,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Acreage              float32  `protobuf:"fixed32,3,opt,name=Acreage,proto3" json:"Acreage,omitempty"`
	State                int32    `protobuf:"varint,4,opt,name=State,proto3" json:"State,omitempty"`
	Rental               int32    `protobuf:"varint,5,opt,name=Rental,proto3" json:"Rental,omitempty"`
	OperatorID           int64    `protobuf:"varint,6,opt,name=OperatorID,proto3" json:"OperatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HouseCommon) Reset()         { *m = HouseCommon{} }
func (m *HouseCommon) String() string { return proto.CompactTextString(m) }
func (*HouseCommon) ProtoMessage()    {}
func (*HouseCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{21}
}

func (m *HouseCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HouseCommon.Unmarshal(m, b)
}
func (m *HouseCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HouseCommon.Marshal(b, m, deterministic)
}
func (m *HouseCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HouseCommon.Merge(m, src)
}
func (m *HouseCommon) XXX_Size() int {
	return xxx_messageInfo_HouseCommon.Size(m)
}
func (m *HouseCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_HouseCommon.DiscardUnknown(m)
}

var xxx_messageInfo_HouseCommon proto.InternalMessageInfo

func (m *HouseCommon) GetBuildingID() int64 {
	if m != nil {
		return m.BuildingID
	}
	return 0
}

func (m *HouseCommon) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *HouseCommon) GetAcreage() float32 {
	if m != nil {
		return m.Acreage
	}
	return 0
}

func (m *HouseCommon) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *HouseCommon) GetRental() int32 {
	if m != nil {
		return m.Rental
	}
	return 0
}

func (m *HouseCommon) GetOperatorID() int64 {
	if m != nil {
		return m.OperatorID
	}
	return 0
}

type AddHouseReq struct {
	House                *HouseCommon `protobuf:"bytes,1,opt,name=House,proto3" json:"House,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddHouseReq) Reset()         { *m = AddHouseReq{} }
func (m *AddHouseReq) String() string { return proto.CompactTextString(m) }
func (*AddHouseReq) ProtoMessage()    {}
func (*AddHouseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{22}
}

func (m *AddHouseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddHouseReq.Unmarshal(m, b)
}
func (m *AddHouseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddHouseReq.Marshal(b, m, deterministic)
}
func (m *AddHouseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddHouseReq.Merge(m, src)
}
func (m *AddHouseReq) XXX_Size() int {
	return xxx_messageInfo_AddHouseReq.Size(m)
}
func (m *AddHouseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddHouseReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddHouseReq proto.InternalMessageInfo

func (m *AddHouseReq) GetHouse() *HouseCommon {
	if m != nil {
		return m.House
	}
	return nil
}

type AddHouseResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddHouseResp) Reset()         { *m = AddHouseResp{} }
func (m *AddHouseResp) String() string { return proto.CompactTextString(m) }
func (*AddHouseResp) ProtoMessage()    {}
func (*AddHouseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{23}
}

func (m *AddHouseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddHouseResp.Unmarshal(m, b)
}
func (m *AddHouseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddHouseResp.Marshal(b, m, deterministic)
}
func (m *AddHouseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddHouseResp.Merge(m, src)
}
func (m *AddHouseResp) XXX_Size() int {
	return xxx_messageInfo_AddHouseResp.Size(m)
}
func (m *AddHouseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddHouseResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddHouseResp proto.InternalMessageInfo

func (m *AddHouseResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type DelHouseReq struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelHouseReq) Reset()         { *m = DelHouseReq{} }
func (m *DelHouseReq) String() string { return proto.CompactTextString(m) }
func (*DelHouseReq) ProtoMessage()    {}
func (*DelHouseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{24}
}

func (m *DelHouseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelHouseReq.Unmarshal(m, b)
}
func (m *DelHouseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelHouseReq.Marshal(b, m, deterministic)
}
func (m *DelHouseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelHouseReq.Merge(m, src)
}
func (m *DelHouseReq) XXX_Size() int {
	return xxx_messageInfo_DelHouseReq.Size(m)
}
func (m *DelHouseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelHouseReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelHouseReq proto.InternalMessageInfo

func (m *DelHouseReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DelHouseResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DelHouseResp) Reset()         { *m = DelHouseResp{} }
func (m *DelHouseResp) String() string { return proto.CompactTextString(m) }
func (*DelHouseResp) ProtoMessage()    {}
func (*DelHouseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{25}
}

func (m *DelHouseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelHouseResp.Unmarshal(m, b)
}
func (m *DelHouseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelHouseResp.Marshal(b, m, deterministic)
}
func (m *DelHouseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelHouseResp.Merge(m, src)
}
func (m *DelHouseResp) XXX_Size() int {
	return xxx_messageInfo_DelHouseResp.Size(m)
}
func (m *DelHouseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelHouseResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelHouseResp proto.InternalMessageInfo

func (m *DelHouseResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetHouseReq struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHouseReq) Reset()         { *m = GetHouseReq{} }
func (m *GetHouseReq) String() string { return proto.CompactTextString(m) }
func (*GetHouseReq) ProtoMessage()    {}
func (*GetHouseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{26}
}

func (m *GetHouseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHouseReq.Unmarshal(m, b)
}
func (m *GetHouseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHouseReq.Marshal(b, m, deterministic)
}
func (m *GetHouseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHouseReq.Merge(m, src)
}
func (m *GetHouseReq) XXX_Size() int {
	return xxx_messageInfo_GetHouseReq.Size(m)
}
func (m *GetHouseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHouseReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetHouseReq proto.InternalMessageInfo

func (m *GetHouseReq) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetHouseResp struct {
	BaseResp             *idl.Resp    `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	House                *HouseCommon `protobuf:"bytes,2,opt,name=House,proto3" json:"House,omitempty"`
	CreatedAt            int64        `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            int64        `protobuf:"varint,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetHouseResp) Reset()         { *m = GetHouseResp{} }
func (m *GetHouseResp) String() string { return proto.CompactTextString(m) }
func (*GetHouseResp) ProtoMessage()    {}
func (*GetHouseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{27}
}

func (m *GetHouseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHouseResp.Unmarshal(m, b)
}
func (m *GetHouseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHouseResp.Marshal(b, m, deterministic)
}
func (m *GetHouseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHouseResp.Merge(m, src)
}
func (m *GetHouseResp) XXX_Size() int {
	return xxx_messageInfo_GetHouseResp.Size(m)
}
func (m *GetHouseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHouseResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetHouseResp proto.InternalMessageInfo

func (m *GetHouseResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetHouseResp) GetHouse() *HouseCommon {
	if m != nil {
		return m.House
	}
	return nil
}

func (m *GetHouseResp) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GetHouseResp) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*CommunityCommon)(nil), "dayan.community.srv.info.CommunityCommon")
	proto.RegisterType((*AddCommunityReq)(nil), "dayan.community.srv.info.AddCommunityReq")
	proto.RegisterType((*AddCommunityResp)(nil), "dayan.community.srv.info.AddCommunityResp")
	proto.RegisterType((*DelCommunityReq)(nil), "dayan.community.srv.info.DelCommunityReq")
	proto.RegisterType((*DelCommunityResp)(nil), "dayan.community.srv.info.DelCommunityResp")
	proto.RegisterType((*GetCommunityReq)(nil), "dayan.community.srv.info.GetCommunityReq")
	proto.RegisterType((*GetCommunityResp)(nil), "dayan.community.srv.info.GetCommunityResp")
	proto.RegisterType((*AssetCommon)(nil), "dayan.community.srv.info.AssetCommon")
	proto.RegisterType((*AddAssetReq)(nil), "dayan.community.srv.info.AddAssetReq")
	proto.RegisterType((*AddAssetResp)(nil), "dayan.community.srv.info.AddAssetResp")
	proto.RegisterType((*DelAssetReq)(nil), "dayan.community.srv.info.DelAssetReq")
	proto.RegisterType((*DelAssetResp)(nil), "dayan.community.srv.info.DelAssetResp")
	proto.RegisterType((*GetAssetReq)(nil), "dayan.community.srv.info.GetAssetReq")
	proto.RegisterType((*GetAssetResp)(nil), "dayan.community.srv.info.GetAssetResp")
	proto.RegisterType((*BuildingCommon)(nil), "dayan.community.srv.info.BuildingCommon")
	proto.RegisterType((*AddBuildingReq)(nil), "dayan.community.srv.info.AddBuildingReq")
	proto.RegisterType((*AddBuildingResp)(nil), "dayan.community.srv.info.AddBuildingResp")
	proto.RegisterType((*DelBuilingReq)(nil), "dayan.community.srv.info.DelBuilingReq")
	proto.RegisterType((*DelBuilingResp)(nil), "dayan.community.srv.info.DelBuilingResp")
	proto.RegisterType((*GetBuildingReq)(nil), "dayan.community.srv.info.GetBuildingReq")
	proto.RegisterType((*GetBuildingResp)(nil), "dayan.community.srv.info.GetBuildingResp")
	proto.RegisterType((*HouseCommon)(nil), "dayan.community.srv.info.HouseCommon")
	proto.RegisterType((*AddHouseReq)(nil), "dayan.community.srv.info.AddHouseReq")
	proto.RegisterType((*AddHouseResp)(nil), "dayan.community.srv.info.AddHouseResp")
	proto.RegisterType((*DelHouseReq)(nil), "dayan.community.srv.info.DelHouseReq")
	proto.RegisterType((*DelHouseResp)(nil), "dayan.community.srv.info.DelHouseResp")
	proto.RegisterType((*GetHouseReq)(nil), "dayan.community.srv.info.GetHouseReq")
	proto.RegisterType((*GetHouseResp)(nil), "dayan.community.srv.info.GetHouseResp")
}

func init() { proto.RegisterFile("info.proto", fileDescriptor_f140d5b28dddb141) }

var fileDescriptor_f140d5b28dddb141 = []byte{
	// 1024 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x51, 0x8f, 0xe3, 0x34,
	0x10, 0x56, 0xd2, 0x76, 0xaf, 0x9d, 0x76, 0xbb, 0x2b, 0x0b, 0xa1, 0xa8, 0x82, 0xa3, 0x8a, 0x74,
	0xb7, 0x5d, 0x1e, 0xfa, 0x70, 0x27, 0x21, 0x04, 0x4f, 0xdd, 0x06, 0x95, 0x22, 0xc4, 0xad, 0x7c,
	0x3a, 0xa4, 0x43, 0x3c, 0x90, 0x6d, 0xbc, 0x25, 0x22, 0x9b, 0x94, 0xc4, 0xbb, 0xd2, 0x3e, 0xf1,
	0x0b, 0x90, 0xf8, 0x1b, 0x3c, 0xc1, 0x3f, 0xe0, 0x57, 0xf0, 0x7f, 0x90, 0xc7, 0x76, 0xe2, 0xa4,
	0xda, 0x34, 0x29, 0x6f, 0x9e, 0xc9, 0xe7, 0xb1, 0x3d, 0xf3, 0xf9, 0x1b, 0x07, 0x20, 0x8c, 0x6f,
	0x93, 0xf9, 0x2e, 0x4d, 0x78, 0x42, 0x9c, 0xc0, 0x7f, 0xf4, 0xe3, 0xf9, 0x26, 0xb9, 0xbb, 0xbb,
	0x8f, 0x43, 0xfe, 0x38, 0xcf, 0xd2, 0x87, 0xb9, 0xf8, 0x3e, 0x81, 0x1b, 0x3f, 0x63, 0x12, 0xe5,
	0xfe, 0xde, 0x81, 0xb3, 0xa5, 0x86, 0x88, 0x41, 0x12, 0x13, 0x02, 0xdd, 0xef, 0xfc, 0x3b, 0xe6,
	0x58, 0x53, 0x6b, 0x36, 0xa0, 0x38, 0x26, 0x13, 0xe8, 0x5f, 0xa7, 0xc9, 0x43, 0x18, 0x6f, 0x98,
	0x63, 0xa3, 0x3f, 0xb7, 0x05, 0x7e, 0x19, 0xf2, 0x47, 0xa7, 0x23, 0xf1, 0x62, 0x4c, 0x3e, 0x84,
	0x13, 0xca, 0xb6, 0x61, 0x12, 0x3b, 0x5d, 0xf4, 0x2a, 0x4b, 0xf8, 0xdf, 0xf2, 0x94, 0x31, 0xee,
	0xf4, 0xa4, 0x5f, 0x5a, 0xe4, 0x23, 0x18, 0x2c, 0x93, 0xfb, 0x78, 0x13, 0x46, 0x6b, 0xcf, 0x39,
	0x99, 0x5a, 0xb3, 0x0e, 0x2d, 0x1c, 0xe4, 0x03, 0xe8, 0xbd, 0x49, 0xb7, 0x6b, 0xcf, 0x79, 0x86,
	0x5f, 0xa4, 0x41, 0x9e, 0x03, 0x7c, 0x9d, 0xdc, 0x67, 0x4c, 0xe0, 0xb8, 0xd3, 0x9f, 0x5a, 0xb3,
	0x1e, 0x35, 0x3c, 0xc4, 0x85, 0xd1, 0xf2, 0x67, 0xb6, 0xf9, 0x65, 0x1d, 0x4b, 0xc4, 0x00, 0x11,
	0x25, 0x9f, 0xc0, 0x5c, 0xdd, 0x87, 0x51, 0x10, 0xc6, 0xdb, 0x45, 0xca, 0x7c, 0x07, 0x24, 0xc6,
	0xf4, 0x09, 0xcc, 0x2a, 0x65, 0x2c, 0xd6, 0x98, 0xa1, 0xc4, 0x98, 0x3e, 0x72, 0x0e, 0x9d, 0x6f,
	0x93, 0x8d, 0x33, 0x9a, 0x76, 0x66, 0x36, 0x15, 0x43, 0xb1, 0xe7, 0xb7, 0xdc, 0xe7, 0xcc, 0x39,
	0x45, 0xb8, 0x34, 0xc4, 0x9e, 0xdf, 0xec, 0x58, 0xea, 0xf3, 0x24, 0x5d, 0x7b, 0xce, 0x18, 0x8f,
	0x63, 0x78, 0xdc, 0x1f, 0xe0, 0x6c, 0x11, 0x04, 0x79, 0x45, 0x28, 0xfb, 0x95, 0xac, 0x44, 0x6a,
	0x94, 0x8d, 0x35, 0x19, 0xbe, 0xba, 0x9c, 0x3f, 0x55, 0xdc, 0x79, 0xa5, 0x98, 0xb4, 0x98, 0xeb,
	0xfe, 0x08, 0xe7, 0xe5, 0xd8, 0xd9, 0x8e, 0xbc, 0x84, 0xfe, 0x95, 0x9f, 0x31, 0x31, 0x56, 0xb1,
	0x61, 0x8e, 0xf4, 0x10, 0x1e, 0x9a, 0x7f, 0x23, 0x53, 0x18, 0xe6, 0x13, 0xd7, 0x1e, 0x52, 0xa0,
	0x43, 0x4d, 0x97, 0xfb, 0x1a, 0xce, 0x3c, 0x16, 0x95, 0x76, 0x5e, 0x99, 0x64, 0xed, 0x4f, 0xfa,
	0x02, 0xce, 0xcb, 0x93, 0x9a, 0x6f, 0x49, 0x2c, 0xb8, 0x62, 0xbc, 0xe5, 0x82, 0xff, 0x58, 0x70,
	0x5e, 0x9e, 0xd5, 0x22, 0x09, 0xa5, 0x4a, 0xd8, 0xc7, 0x57, 0x02, 0xd9, 0x9e, 0x32, 0x9f, 0xb3,
	0x60, 0xc1, 0xf1, 0xda, 0x08, 0xb6, 0x6b, 0x87, 0xf8, 0xfa, 0x6e, 0x17, 0xa8, 0xaf, 0x5d, 0xf9,
	0x35, 0x77, 0xb8, 0xff, 0x5a, 0x30, 0x5c, 0x64, 0x99, 0x3c, 0x83, 0xba, 0x51, 0x2c, 0x0d, 0xfd,
	0x48, 0xdd, 0x57, 0x65, 0x89, 0x1b, 0xbb, 0xf4, 0x39, 0xdb, 0x26, 0xa9, 0xdc, 0x6b, 0x8f, 0xe6,
	0x76, 0xc1, 0xcd, 0x8e, 0xc9, 0xcd, 0x4a, 0xf6, 0xba, 0x7b, 0xd9, 0x13, 0x2c, 0x8f, 0x92, 0x8d,
	0xba, 0xba, 0x62, 0x28, 0x22, 0x5d, 0xa5, 0x7e, 0x1c, 0xe0, 0x9d, 0x1d, 0x50, 0x69, 0x08, 0x45,
	0xf0, 0x58, 0xb6, 0xc1, 0xeb, 0x3a, 0xa0, 0x38, 0xae, 0x30, 0xbf, 0xbf, 0xc7, 0xfc, 0x6f, 0x60,
	0xb8, 0x08, 0x02, 0x3c, 0x99, 0x28, 0xe5, 0x97, 0xd0, 0xc3, 0xb1, 0x2a, 0xc8, 0x8b, 0xa7, 0xf3,
	0x6c, 0x24, 0x83, 0xca, 0x39, 0xee, 0x35, 0x8c, 0x8a, 0x58, 0x2d, 0x0a, 0xec, 0xc0, 0x33, 0x9c,
	0x94, 0x33, 0x5c, 0x9b, 0xee, 0x05, 0x0c, 0x3d, 0x16, 0xe5, 0xbb, 0x33, 0x80, 0x56, 0x19, 0xf8,
	0x19, 0x8c, 0x0a, 0x60, 0x0b, 0x36, 0x5f, 0xc0, 0x70, 0xc5, 0x78, 0x83, 0x05, 0x32, 0x18, 0x15,
	0xc0, 0x16, 0x67, 0xcb, 0x13, 0x6a, 0x1f, 0x91, 0xd0, 0xbf, 0x2d, 0x18, 0x6b, 0x4d, 0xac, 0xe9,
	0x12, 0x07, 0x55, 0x42, 0xb0, 0xf5, 0x9a, 0xa5, 0x61, 0x12, 0x28, 0xea, 0x29, 0x4b, 0xb0, 0xe3,
	0xab, 0x88, 0x3d, 0x28, 0x76, 0x74, 0xa7, 0x1d, 0xc1, 0x8e, 0xc2, 0xa3, 0xf5, 0xb5, 0x57, 0xe8,
	0x6b, 0x99, 0x4f, 0x27, 0x7b, 0x7c, 0xfa, 0x1e, 0xc6, 0x8b, 0x20, 0xd0, 0x9b, 0x16, 0x39, 0xf5,
	0xa0, 0xaf, 0x4d, 0x95, 0xa9, 0xd9, 0xd3, 0x49, 0x28, 0x9f, 0x96, 0xe6, 0x33, 0xdd, 0x35, 0x2a,
	0x74, 0x11, 0xb7, 0x45, 0x09, 0xc6, 0x60, 0xe7, 0x59, 0xb1, 0xd7, 0x9e, 0xfb, 0x09, 0x9c, 0x7a,
	0x2c, 0x12, 0xa1, 0xd4, 0x0e, 0x25, 0xc0, 0xca, 0x01, 0x9f, 0xc3, 0xd8, 0x04, 0xb4, 0xa0, 0xd3,
	0x14, 0xc6, 0x2b, 0xc6, 0xcd, 0xd3, 0x57, 0x63, 0xff, 0x86, 0xf2, 0x79, 0xd4, 0x39, 0xcc, 0x44,
	0xda, 0x47, 0x27, 0xf2, 0x4f, 0x0b, 0x86, 0xaa, 0x5b, 0x23, 0xa1, 0x9e, 0x03, 0xe8, 0x6f, 0xf9,
	0x46, 0x0d, 0x8f, 0x20, 0xdc, 0xbb, 0x38, 0xe4, 0xea, 0xf9, 0x81, 0x63, 0xbc, 0x26, 0x9b, 0x94,
	0xf9, 0x5b, 0x29, 0x65, 0x36, 0xd5, 0x66, 0x21, 0x71, 0x5d, 0x53, 0xe2, 0xf0, 0x59, 0x12, 0x73,
	0x3f, 0x42, 0x0d, 0xeb, 0x51, 0x65, 0x1d, 0x24, 0x93, 0x14, 0x27, 0xdc, 0xad, 0x12, 0x27, 0x1c,
	0x1f, 0x16, 0x27, 0xe3, 0x80, 0x54, 0xce, 0x11, 0x0a, 0x51, 0xc4, 0x6a, 0x51, 0xd2, 0x8f, 0x51,
	0x82, 0xf2, 0x3d, 0x54, 0xeb, 0x29, 0x85, 0xe7, 0xa8, 0xb0, 0x2b, 0xc6, 0x9f, 0x0c, 0xfb, 0x97,
	0x85, 0x7a, 0xd3, 0x3a, 0x6e, 0x91, 0x23, 0xbb, 0x7d, 0x8e, 0xfe, 0x4f, 0x83, 0x7c, 0xf5, 0xc7,
	0x00, 0x4e, 0x0b, 0xc9, 0x89, 0x6f, 0x13, 0xc2, 0x30, 0xe3, 0x45, 0xfb, 0xad, 0x69, 0xda, 0x95,
	0xc7, 0xd7, 0xe4, 0xd3, 0xa6, 0xd0, 0x6c, 0x27, 0x96, 0x31, 0x1f, 0x33, 0x75, 0xcb, 0x54, 0x5e,
	0x4a, 0x75, 0xcb, 0xec, 0xbd, 0x8f, 0x18, 0x16, 0xa4, 0xd1, 0x32, 0x95, 0xf7, 0x51, 0xdd, 0x32,
	0x7b, 0x8f, 0xa2, 0xf7, 0xd0, 0xd7, 0x3d, 0x94, 0xbc, 0xa8, 0xcd, 0x82, 0x6e, 0x5a, 0x93, 0x97,
	0x4d, 0x60, 0x32, 0xb4, 0xee, 0x91, 0x75, 0xa1, 0x8d, 0x86, 0x5b, 0x17, 0xba, 0xd4, 0x6e, 0xdf,
	0x43, 0x5f, 0x77, 0xc7, 0xba, 0xd0, 0x46, 0xab, 0xad, 0x0b, 0x5d, 0x6a, 0xb4, 0x37, 0xa8, 0x01,
	0x5a, 0x90, 0xc8, 0xac, 0xf6, 0xb0, 0x86, 0xf2, 0x4e, 0x2e, 0x1b, 0x22, 0xb3, 0x1d, 0xf9, 0x09,
	0xef, 0x78, 0xbe, 0xc6, 0x45, 0xed, 0xa9, 0x8b, 0xc6, 0x31, 0x99, 0x35, 0x03, 0xca, 0x53, 0x18,
	0xb2, 0x5f, 0x77, 0x8a, 0x72, 0xff, 0x98, 0x5c, 0x36, 0x44, 0xe6, 0xd4, 0x91, 0x37, 0xb9, 0x9e,
	0x3a, 0x5a, 0x76, 0x0e, 0x50, 0xa7, 0x50, 0x1f, 0x49, 0x9d, 0x83, 0xa1, 0x0d, 0xa1, 0x3c, 0x40,
	0x9d, 0x52, 0x68, 0x2d, 0x74, 0x07, 0xa8, 0xd3, 0x24, 0xb4, 0xa9, 0x99, 0x37, 0x27, 0xf8, 0xb3,
	0xfd, 0xfa, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x60, 0x6c, 0x91, 0xa0, 0xa0, 0x0f, 0x00, 0x00,
}
