// Code generated by protoc-gen-go. DO NOT EDIT.
// source: info.proto

package dayan_community_srv_info

import (
	fmt "fmt"
	idl "github.com/dy-dayan/community-srv-info/idl"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommunityCommon struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Province             string    `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	City                 string    `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Region               string    `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Street               string    `protobuf:"bytes,6,opt,name=street,proto3" json:"street,omitempty"`
	SerialNumber         string    `protobuf:"bytes,7,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	OrgID                int64     `protobuf:"varint,8,opt,name=orgID,proto3" json:"orgID,omitempty"`
	HouseCount           int32     `protobuf:"varint,9,opt,name=houseCount,proto3" json:"houseCount,omitempty"`
	CheckInCount         int32     `protobuf:"varint,11,opt,name=checkInCount,proto3" json:"checkInCount,omitempty"`
	BuildingArea         float32   `protobuf:"fixed32,12,opt,name=buildingArea,proto3" json:"buildingArea,omitempty"`
	GreeningArea         float32   `protobuf:"fixed32,13,opt,name=greeningArea,proto3" json:"greeningArea,omitempty"`
	Loc                  []float32 `protobuf:"fixed32,14,rep,packed,name=loc,proto3" json:"loc,omitempty"`
	State                int32     `protobuf:"varint,15,opt,name=state,proto3" json:"state,omitempty"`
	SealedState          int32     `protobuf:"varint,16,opt,name=sealedState,proto3" json:"sealedState,omitempty"`
	OperatorID           int64     `protobuf:"varint,17,opt,name=operatorID,proto3" json:"operatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CommunityCommon) Reset()         { *m = CommunityCommon{} }
func (m *CommunityCommon) String() string { return proto.CompactTextString(m) }
func (*CommunityCommon) ProtoMessage()    {}
func (*CommunityCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{0}
}

func (m *CommunityCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityCommon.Unmarshal(m, b)
}
func (m *CommunityCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityCommon.Marshal(b, m, deterministic)
}
func (m *CommunityCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityCommon.Merge(m, src)
}
func (m *CommunityCommon) XXX_Size() int {
	return xxx_messageInfo_CommunityCommon.Size(m)
}
func (m *CommunityCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityCommon.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityCommon proto.InternalMessageInfo

func (m *CommunityCommon) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CommunityCommon) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommunityCommon) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *CommunityCommon) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CommunityCommon) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *CommunityCommon) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *CommunityCommon) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *CommunityCommon) GetOrgID() int64 {
	if m != nil {
		return m.OrgID
	}
	return 0
}

func (m *CommunityCommon) GetHouseCount() int32 {
	if m != nil {
		return m.HouseCount
	}
	return 0
}

func (m *CommunityCommon) GetCheckInCount() int32 {
	if m != nil {
		return m.CheckInCount
	}
	return 0
}

func (m *CommunityCommon) GetBuildingArea() float32 {
	if m != nil {
		return m.BuildingArea
	}
	return 0
}

func (m *CommunityCommon) GetGreeningArea() float32 {
	if m != nil {
		return m.GreeningArea
	}
	return 0
}

func (m *CommunityCommon) GetLoc() []float32 {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *CommunityCommon) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *CommunityCommon) GetSealedState() int32 {
	if m != nil {
		return m.SealedState
	}
	return 0
}

func (m *CommunityCommon) GetOperatorID() int64 {
	if m != nil {
		return m.OperatorID
	}
	return 0
}

type Community struct {
	Common               *CommunityCommon `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	UpdatedAt            int64            `protobuf:"varint,2,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	CreatedAt            int64            `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Community) Reset()         { *m = Community{} }
func (m *Community) String() string { return proto.CompactTextString(m) }
func (*Community) ProtoMessage()    {}
func (*Community) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{1}
}

func (m *Community) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Community.Unmarshal(m, b)
}
func (m *Community) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Community.Marshal(b, m, deterministic)
}
func (m *Community) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Community.Merge(m, src)
}
func (m *Community) XXX_Size() int {
	return xxx_messageInfo_Community.Size(m)
}
func (m *Community) XXX_DiscardUnknown() {
	xxx_messageInfo_Community.DiscardUnknown(m)
}

var xxx_messageInfo_Community proto.InternalMessageInfo

func (m *Community) GetCommon() *CommunityCommon {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *Community) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Community) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type AddCommunityReq struct {
	Community            *CommunityCommon `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddCommunityReq) Reset()         { *m = AddCommunityReq{} }
func (m *AddCommunityReq) String() string { return proto.CompactTextString(m) }
func (*AddCommunityReq) ProtoMessage()    {}
func (*AddCommunityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{2}
}

func (m *AddCommunityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommunityReq.Unmarshal(m, b)
}
func (m *AddCommunityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommunityReq.Marshal(b, m, deterministic)
}
func (m *AddCommunityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommunityReq.Merge(m, src)
}
func (m *AddCommunityReq) XXX_Size() int {
	return xxx_messageInfo_AddCommunityReq.Size(m)
}
func (m *AddCommunityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommunityReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommunityReq proto.InternalMessageInfo

func (m *AddCommunityReq) GetCommunity() *CommunityCommon {
	if m != nil {
		return m.Community
	}
	return nil
}

type AddCommunityResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	CommunityID          int64     `protobuf:"varint,2,opt,name=communityID,proto3" json:"communityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddCommunityResp) Reset()         { *m = AddCommunityResp{} }
func (m *AddCommunityResp) String() string { return proto.CompactTextString(m) }
func (*AddCommunityResp) ProtoMessage()    {}
func (*AddCommunityResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{3}
}

func (m *AddCommunityResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommunityResp.Unmarshal(m, b)
}
func (m *AddCommunityResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommunityResp.Marshal(b, m, deterministic)
}
func (m *AddCommunityResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommunityResp.Merge(m, src)
}
func (m *AddCommunityResp) XXX_Size() int {
	return xxx_messageInfo_AddCommunityResp.Size(m)
}
func (m *AddCommunityResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommunityResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommunityResp proto.InternalMessageInfo

func (m *AddCommunityResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *AddCommunityResp) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

type DelCommunityReq struct {
	CommunityID          int64    `protobuf:"varint,1,opt,name=communityID,proto3" json:"communityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelCommunityReq) Reset()         { *m = DelCommunityReq{} }
func (m *DelCommunityReq) String() string { return proto.CompactTextString(m) }
func (*DelCommunityReq) ProtoMessage()    {}
func (*DelCommunityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{4}
}

func (m *DelCommunityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCommunityReq.Unmarshal(m, b)
}
func (m *DelCommunityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCommunityReq.Marshal(b, m, deterministic)
}
func (m *DelCommunityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCommunityReq.Merge(m, src)
}
func (m *DelCommunityReq) XXX_Size() int {
	return xxx_messageInfo_DelCommunityReq.Size(m)
}
func (m *DelCommunityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCommunityReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelCommunityReq proto.InternalMessageInfo

func (m *DelCommunityReq) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

type DelCommunityResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DelCommunityResp) Reset()         { *m = DelCommunityResp{} }
func (m *DelCommunityResp) String() string { return proto.CompactTextString(m) }
func (*DelCommunityResp) ProtoMessage()    {}
func (*DelCommunityResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{5}
}

func (m *DelCommunityResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCommunityResp.Unmarshal(m, b)
}
func (m *DelCommunityResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCommunityResp.Marshal(b, m, deterministic)
}
func (m *DelCommunityResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCommunityResp.Merge(m, src)
}
func (m *DelCommunityResp) XXX_Size() int {
	return xxx_messageInfo_DelCommunityResp.Size(m)
}
func (m *DelCommunityResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCommunityResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelCommunityResp proto.InternalMessageInfo

func (m *DelCommunityResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetCommunityByIDReq struct {
	CommunityID          int64    `protobuf:"varint,1,opt,name=communityID,proto3" json:"communityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommunityByIDReq) Reset()         { *m = GetCommunityByIDReq{} }
func (m *GetCommunityByIDReq) String() string { return proto.CompactTextString(m) }
func (*GetCommunityByIDReq) ProtoMessage()    {}
func (*GetCommunityByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{6}
}

func (m *GetCommunityByIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommunityByIDReq.Unmarshal(m, b)
}
func (m *GetCommunityByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommunityByIDReq.Marshal(b, m, deterministic)
}
func (m *GetCommunityByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommunityByIDReq.Merge(m, src)
}
func (m *GetCommunityByIDReq) XXX_Size() int {
	return xxx_messageInfo_GetCommunityByIDReq.Size(m)
}
func (m *GetCommunityByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommunityByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommunityByIDReq proto.InternalMessageInfo

func (m *GetCommunityByIDReq) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

type GetCommunityByIDResp struct {
	BaseResp             *idl.Resp  `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	Community            *Community `protobuf:"bytes,2,opt,name=community,proto3" json:"community,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetCommunityByIDResp) Reset()         { *m = GetCommunityByIDResp{} }
func (m *GetCommunityByIDResp) String() string { return proto.CompactTextString(m) }
func (*GetCommunityByIDResp) ProtoMessage()    {}
func (*GetCommunityByIDResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{7}
}

func (m *GetCommunityByIDResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommunityByIDResp.Unmarshal(m, b)
}
func (m *GetCommunityByIDResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommunityByIDResp.Marshal(b, m, deterministic)
}
func (m *GetCommunityByIDResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommunityByIDResp.Merge(m, src)
}
func (m *GetCommunityByIDResp) XXX_Size() int {
	return xxx_messageInfo_GetCommunityByIDResp.Size(m)
}
func (m *GetCommunityByIDResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommunityByIDResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommunityByIDResp proto.InternalMessageInfo

func (m *GetCommunityByIDResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetCommunityByIDResp) GetCommunity() *Community {
	if m != nil {
		return m.Community
	}
	return nil
}

type GetCommunityReq struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommunityReq) Reset()         { *m = GetCommunityReq{} }
func (m *GetCommunityReq) String() string { return proto.CompactTextString(m) }
func (*GetCommunityReq) ProtoMessage()    {}
func (*GetCommunityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{8}
}

func (m *GetCommunityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommunityReq.Unmarshal(m, b)
}
func (m *GetCommunityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommunityReq.Marshal(b, m, deterministic)
}
func (m *GetCommunityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommunityReq.Merge(m, src)
}
func (m *GetCommunityReq) XXX_Size() int {
	return xxx_messageInfo_GetCommunityReq.Size(m)
}
func (m *GetCommunityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommunityReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommunityReq proto.InternalMessageInfo

func (m *GetCommunityReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetCommunityReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type GetCommunityResp struct {
	BaseResp             *idl.Resp    `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	Communitys           []*Community `protobuf:"bytes,2,rep,name=communitys,proto3" json:"communitys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetCommunityResp) Reset()         { *m = GetCommunityResp{} }
func (m *GetCommunityResp) String() string { return proto.CompactTextString(m) }
func (*GetCommunityResp) ProtoMessage()    {}
func (*GetCommunityResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{9}
}

func (m *GetCommunityResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommunityResp.Unmarshal(m, b)
}
func (m *GetCommunityResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommunityResp.Marshal(b, m, deterministic)
}
func (m *GetCommunityResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommunityResp.Merge(m, src)
}
func (m *GetCommunityResp) XXX_Size() int {
	return xxx_messageInfo_GetCommunityResp.Size(m)
}
func (m *GetCommunityResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommunityResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommunityResp proto.InternalMessageInfo

func (m *GetCommunityResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetCommunityResp) GetCommunitys() []*Community {
	if m != nil {
		return m.Communitys
	}
	return nil
}

type GetCommunityByLocReq struct {
	Limit                int32     `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32     `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Loc                  []float32 `protobuf:"fixed32,3,rep,packed,name=loc,proto3" json:"loc,omitempty"`
	Distance             float32   `protobuf:"fixed32,4,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCommunityByLocReq) Reset()         { *m = GetCommunityByLocReq{} }
func (m *GetCommunityByLocReq) String() string { return proto.CompactTextString(m) }
func (*GetCommunityByLocReq) ProtoMessage()    {}
func (*GetCommunityByLocReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{10}
}

func (m *GetCommunityByLocReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommunityByLocReq.Unmarshal(m, b)
}
func (m *GetCommunityByLocReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommunityByLocReq.Marshal(b, m, deterministic)
}
func (m *GetCommunityByLocReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommunityByLocReq.Merge(m, src)
}
func (m *GetCommunityByLocReq) XXX_Size() int {
	return xxx_messageInfo_GetCommunityByLocReq.Size(m)
}
func (m *GetCommunityByLocReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommunityByLocReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommunityByLocReq proto.InternalMessageInfo

func (m *GetCommunityByLocReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetCommunityByLocReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetCommunityByLocReq) GetLoc() []float32 {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *GetCommunityByLocReq) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type GetCommunityByLocResp struct {
	BaseResp             *idl.Resp    `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	Communitys           []*Community `protobuf:"bytes,2,rep,name=communitys,proto3" json:"communitys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetCommunityByLocResp) Reset()         { *m = GetCommunityByLocResp{} }
func (m *GetCommunityByLocResp) String() string { return proto.CompactTextString(m) }
func (*GetCommunityByLocResp) ProtoMessage()    {}
func (*GetCommunityByLocResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{11}
}

func (m *GetCommunityByLocResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommunityByLocResp.Unmarshal(m, b)
}
func (m *GetCommunityByLocResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommunityByLocResp.Marshal(b, m, deterministic)
}
func (m *GetCommunityByLocResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommunityByLocResp.Merge(m, src)
}
func (m *GetCommunityByLocResp) XXX_Size() int {
	return xxx_messageInfo_GetCommunityByLocResp.Size(m)
}
func (m *GetCommunityByLocResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommunityByLocResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommunityByLocResp proto.InternalMessageInfo

func (m *GetCommunityByLocResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetCommunityByLocResp) GetCommunitys() []*Community {
	if m != nil {
		return m.Communitys
	}
	return nil
}

type AssetCommon struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SerialNumber         string   `protobuf:"bytes,2,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	Category             int32    `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	State                int32    `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	CommunityID          int64    `protobuf:"varint,5,opt,name=communityID,proto3" json:"communityID,omitempty"`
	Loc                  string   `protobuf:"bytes,6,opt,name=loc,proto3" json:"loc,omitempty"`
	Brand                string   `protobuf:"bytes,7,opt,name=brand,proto3" json:"brand,omitempty"`
	Desc                 string   `protobuf:"bytes,8,opt,name=desc,proto3" json:"desc,omitempty"`
	OperatorID           int64    `protobuf:"varint,9,opt,name=operatorID,proto3" json:"operatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetCommon) Reset()         { *m = AssetCommon{} }
func (m *AssetCommon) String() string { return proto.CompactTextString(m) }
func (*AssetCommon) ProtoMessage()    {}
func (*AssetCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{12}
}

func (m *AssetCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetCommon.Unmarshal(m, b)
}
func (m *AssetCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetCommon.Marshal(b, m, deterministic)
}
func (m *AssetCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetCommon.Merge(m, src)
}
func (m *AssetCommon) XXX_Size() int {
	return xxx_messageInfo_AssetCommon.Size(m)
}
func (m *AssetCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetCommon.DiscardUnknown(m)
}

var xxx_messageInfo_AssetCommon proto.InternalMessageInfo

func (m *AssetCommon) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AssetCommon) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *AssetCommon) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *AssetCommon) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *AssetCommon) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

func (m *AssetCommon) GetLoc() string {
	if m != nil {
		return m.Loc
	}
	return ""
}

func (m *AssetCommon) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *AssetCommon) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *AssetCommon) GetOperatorID() int64 {
	if m != nil {
		return m.OperatorID
	}
	return 0
}

type Asset struct {
	Common               *AssetCommon `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	CreatedAt            int64        `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64        `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{13}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetCommon() *AssetCommon {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *Asset) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Asset) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type AddAssetReq struct {
	Asset                *AssetCommon `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddAssetReq) Reset()         { *m = AddAssetReq{} }
func (m *AddAssetReq) String() string { return proto.CompactTextString(m) }
func (*AddAssetReq) ProtoMessage()    {}
func (*AddAssetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{14}
}

func (m *AddAssetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAssetReq.Unmarshal(m, b)
}
func (m *AddAssetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAssetReq.Marshal(b, m, deterministic)
}
func (m *AddAssetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAssetReq.Merge(m, src)
}
func (m *AddAssetReq) XXX_Size() int {
	return xxx_messageInfo_AddAssetReq.Size(m)
}
func (m *AddAssetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAssetReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddAssetReq proto.InternalMessageInfo

func (m *AddAssetReq) GetAsset() *AssetCommon {
	if m != nil {
		return m.Asset
	}
	return nil
}

type AddAssetResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	AssetID              int64     `protobuf:"varint,2,opt,name=assetID,proto3" json:"assetID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddAssetResp) Reset()         { *m = AddAssetResp{} }
func (m *AddAssetResp) String() string { return proto.CompactTextString(m) }
func (*AddAssetResp) ProtoMessage()    {}
func (*AddAssetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{15}
}

func (m *AddAssetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAssetResp.Unmarshal(m, b)
}
func (m *AddAssetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAssetResp.Marshal(b, m, deterministic)
}
func (m *AddAssetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAssetResp.Merge(m, src)
}
func (m *AddAssetResp) XXX_Size() int {
	return xxx_messageInfo_AddAssetResp.Size(m)
}
func (m *AddAssetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAssetResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddAssetResp proto.InternalMessageInfo

func (m *AddAssetResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *AddAssetResp) GetAssetID() int64 {
	if m != nil {
		return m.AssetID
	}
	return 0
}

type DelAssetReq struct {
	AssetID              int64    `protobuf:"varint,1,opt,name=assetID,proto3" json:"assetID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelAssetReq) Reset()         { *m = DelAssetReq{} }
func (m *DelAssetReq) String() string { return proto.CompactTextString(m) }
func (*DelAssetReq) ProtoMessage()    {}
func (*DelAssetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{16}
}

func (m *DelAssetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelAssetReq.Unmarshal(m, b)
}
func (m *DelAssetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelAssetReq.Marshal(b, m, deterministic)
}
func (m *DelAssetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelAssetReq.Merge(m, src)
}
func (m *DelAssetReq) XXX_Size() int {
	return xxx_messageInfo_DelAssetReq.Size(m)
}
func (m *DelAssetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelAssetReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelAssetReq proto.InternalMessageInfo

func (m *DelAssetReq) GetAssetID() int64 {
	if m != nil {
		return m.AssetID
	}
	return 0
}

type DelAssetResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DelAssetResp) Reset()         { *m = DelAssetResp{} }
func (m *DelAssetResp) String() string { return proto.CompactTextString(m) }
func (*DelAssetResp) ProtoMessage()    {}
func (*DelAssetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{17}
}

func (m *DelAssetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelAssetResp.Unmarshal(m, b)
}
func (m *DelAssetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelAssetResp.Marshal(b, m, deterministic)
}
func (m *DelAssetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelAssetResp.Merge(m, src)
}
func (m *DelAssetResp) XXX_Size() int {
	return xxx_messageInfo_DelAssetResp.Size(m)
}
func (m *DelAssetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelAssetResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelAssetResp proto.InternalMessageInfo

func (m *DelAssetResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetAssetByIDReq struct {
	AssetID              int64    `protobuf:"varint,1,opt,name=assetID,proto3" json:"assetID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAssetByIDReq) Reset()         { *m = GetAssetByIDReq{} }
func (m *GetAssetByIDReq) String() string { return proto.CompactTextString(m) }
func (*GetAssetByIDReq) ProtoMessage()    {}
func (*GetAssetByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{18}
}

func (m *GetAssetByIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetByIDReq.Unmarshal(m, b)
}
func (m *GetAssetByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetByIDReq.Marshal(b, m, deterministic)
}
func (m *GetAssetByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetByIDReq.Merge(m, src)
}
func (m *GetAssetByIDReq) XXX_Size() int {
	return xxx_messageInfo_GetAssetByIDReq.Size(m)
}
func (m *GetAssetByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetByIDReq proto.InternalMessageInfo

func (m *GetAssetByIDReq) GetAssetID() int64 {
	if m != nil {
		return m.AssetID
	}
	return 0
}

type GetAssetByIDResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	Asset                *Asset    `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetAssetByIDResp) Reset()         { *m = GetAssetByIDResp{} }
func (m *GetAssetByIDResp) String() string { return proto.CompactTextString(m) }
func (*GetAssetByIDResp) ProtoMessage()    {}
func (*GetAssetByIDResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{19}
}

func (m *GetAssetByIDResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetByIDResp.Unmarshal(m, b)
}
func (m *GetAssetByIDResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetByIDResp.Marshal(b, m, deterministic)
}
func (m *GetAssetByIDResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetByIDResp.Merge(m, src)
}
func (m *GetAssetByIDResp) XXX_Size() int {
	return xxx_messageInfo_GetAssetByIDResp.Size(m)
}
func (m *GetAssetByIDResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetByIDResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetByIDResp proto.InternalMessageInfo

func (m *GetAssetByIDResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetAssetByIDResp) GetAsset() *Asset {
	if m != nil {
		return m.Asset
	}
	return nil
}

type GetAssetReq struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	CommunityID          int64    `protobuf:"varint,3,opt,name=communityID,proto3" json:"communityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAssetReq) Reset()         { *m = GetAssetReq{} }
func (m *GetAssetReq) String() string { return proto.CompactTextString(m) }
func (*GetAssetReq) ProtoMessage()    {}
func (*GetAssetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{20}
}

func (m *GetAssetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetReq.Unmarshal(m, b)
}
func (m *GetAssetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetReq.Marshal(b, m, deterministic)
}
func (m *GetAssetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetReq.Merge(m, src)
}
func (m *GetAssetReq) XXX_Size() int {
	return xxx_messageInfo_GetAssetReq.Size(m)
}
func (m *GetAssetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetReq proto.InternalMessageInfo

func (m *GetAssetReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAssetReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetAssetReq) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

type GetAssetResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	Assets               []*Asset  `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetAssetResp) Reset()         { *m = GetAssetResp{} }
func (m *GetAssetResp) String() string { return proto.CompactTextString(m) }
func (*GetAssetResp) ProtoMessage()    {}
func (*GetAssetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{21}
}

func (m *GetAssetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssetResp.Unmarshal(m, b)
}
func (m *GetAssetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssetResp.Marshal(b, m, deterministic)
}
func (m *GetAssetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssetResp.Merge(m, src)
}
func (m *GetAssetResp) XXX_Size() int {
	return xxx_messageInfo_GetAssetResp.Size(m)
}
func (m *GetAssetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssetResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssetResp proto.InternalMessageInfo

func (m *GetAssetResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetAssetResp) GetAssets() []*Asset {
	if m != nil {
		return m.Assets
	}
	return nil
}

type BuildingCommon struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CommunityID          int64     `protobuf:"varint,3,opt,name=communityID,proto3" json:"communityID,omitempty"`
	Period               int32     `protobuf:"varint,4,opt,name=period,proto3" json:"period,omitempty"`
	ElevatorIDs          []int64   `protobuf:"varint,5,rep,packed,name=elevatorIDs,proto3" json:"elevatorIDs,omitempty"`
	Loc                  []float32 `protobuf:"fixed32,6,rep,packed,name=loc,proto3" json:"loc,omitempty"`
	OperatorID           int64     `protobuf:"varint,7,opt,name=operatorID,proto3" json:"operatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BuildingCommon) Reset()         { *m = BuildingCommon{} }
func (m *BuildingCommon) String() string { return proto.CompactTextString(m) }
func (*BuildingCommon) ProtoMessage()    {}
func (*BuildingCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{22}
}

func (m *BuildingCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildingCommon.Unmarshal(m, b)
}
func (m *BuildingCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildingCommon.Marshal(b, m, deterministic)
}
func (m *BuildingCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildingCommon.Merge(m, src)
}
func (m *BuildingCommon) XXX_Size() int {
	return xxx_messageInfo_BuildingCommon.Size(m)
}
func (m *BuildingCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildingCommon.DiscardUnknown(m)
}

var xxx_messageInfo_BuildingCommon proto.InternalMessageInfo

func (m *BuildingCommon) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BuildingCommon) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuildingCommon) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

func (m *BuildingCommon) GetPeriod() int32 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *BuildingCommon) GetElevatorIDs() []int64 {
	if m != nil {
		return m.ElevatorIDs
	}
	return nil
}

func (m *BuildingCommon) GetLoc() []float32 {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *BuildingCommon) GetOperatorID() int64 {
	if m != nil {
		return m.OperatorID
	}
	return 0
}

type Building struct {
	Common               *BuildingCommon `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	CreatedAt            int64           `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64           `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Building) Reset()         { *m = Building{} }
func (m *Building) String() string { return proto.CompactTextString(m) }
func (*Building) ProtoMessage()    {}
func (*Building) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{23}
}

func (m *Building) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Building.Unmarshal(m, b)
}
func (m *Building) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Building.Marshal(b, m, deterministic)
}
func (m *Building) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Building.Merge(m, src)
}
func (m *Building) XXX_Size() int {
	return xxx_messageInfo_Building.Size(m)
}
func (m *Building) XXX_DiscardUnknown() {
	xxx_messageInfo_Building.DiscardUnknown(m)
}

var xxx_messageInfo_Building proto.InternalMessageInfo

func (m *Building) GetCommon() *BuildingCommon {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *Building) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Building) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type AddBuildingReq struct {
	Building             *BuildingCommon `protobuf:"bytes,1,opt,name=building,proto3" json:"building,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddBuildingReq) Reset()         { *m = AddBuildingReq{} }
func (m *AddBuildingReq) String() string { return proto.CompactTextString(m) }
func (*AddBuildingReq) ProtoMessage()    {}
func (*AddBuildingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{24}
}

func (m *AddBuildingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBuildingReq.Unmarshal(m, b)
}
func (m *AddBuildingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBuildingReq.Marshal(b, m, deterministic)
}
func (m *AddBuildingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBuildingReq.Merge(m, src)
}
func (m *AddBuildingReq) XXX_Size() int {
	return xxx_messageInfo_AddBuildingReq.Size(m)
}
func (m *AddBuildingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBuildingReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddBuildingReq proto.InternalMessageInfo

func (m *AddBuildingReq) GetBuilding() *BuildingCommon {
	if m != nil {
		return m.Building
	}
	return nil
}

type AddBuildingResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	Id                   int64     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddBuildingResp) Reset()         { *m = AddBuildingResp{} }
func (m *AddBuildingResp) String() string { return proto.CompactTextString(m) }
func (*AddBuildingResp) ProtoMessage()    {}
func (*AddBuildingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{25}
}

func (m *AddBuildingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBuildingResp.Unmarshal(m, b)
}
func (m *AddBuildingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBuildingResp.Marshal(b, m, deterministic)
}
func (m *AddBuildingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBuildingResp.Merge(m, src)
}
func (m *AddBuildingResp) XXX_Size() int {
	return xxx_messageInfo_AddBuildingResp.Size(m)
}
func (m *AddBuildingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBuildingResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddBuildingResp proto.InternalMessageInfo

func (m *AddBuildingResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *AddBuildingResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DelBuildingReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelBuildingReq) Reset()         { *m = DelBuildingReq{} }
func (m *DelBuildingReq) String() string { return proto.CompactTextString(m) }
func (*DelBuildingReq) ProtoMessage()    {}
func (*DelBuildingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{26}
}

func (m *DelBuildingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelBuildingReq.Unmarshal(m, b)
}
func (m *DelBuildingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelBuildingReq.Marshal(b, m, deterministic)
}
func (m *DelBuildingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelBuildingReq.Merge(m, src)
}
func (m *DelBuildingReq) XXX_Size() int {
	return xxx_messageInfo_DelBuildingReq.Size(m)
}
func (m *DelBuildingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelBuildingReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelBuildingReq proto.InternalMessageInfo

func (m *DelBuildingReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DelBuildingResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DelBuildingResp) Reset()         { *m = DelBuildingResp{} }
func (m *DelBuildingResp) String() string { return proto.CompactTextString(m) }
func (*DelBuildingResp) ProtoMessage()    {}
func (*DelBuildingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{27}
}

func (m *DelBuildingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelBuildingResp.Unmarshal(m, b)
}
func (m *DelBuildingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelBuildingResp.Marshal(b, m, deterministic)
}
func (m *DelBuildingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelBuildingResp.Merge(m, src)
}
func (m *DelBuildingResp) XXX_Size() int {
	return xxx_messageInfo_DelBuildingResp.Size(m)
}
func (m *DelBuildingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelBuildingResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelBuildingResp proto.InternalMessageInfo

func (m *DelBuildingResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetBuildingByIDReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuildingByIDReq) Reset()         { *m = GetBuildingByIDReq{} }
func (m *GetBuildingByIDReq) String() string { return proto.CompactTextString(m) }
func (*GetBuildingByIDReq) ProtoMessage()    {}
func (*GetBuildingByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{28}
}

func (m *GetBuildingByIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildingByIDReq.Unmarshal(m, b)
}
func (m *GetBuildingByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildingByIDReq.Marshal(b, m, deterministic)
}
func (m *GetBuildingByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildingByIDReq.Merge(m, src)
}
func (m *GetBuildingByIDReq) XXX_Size() int {
	return xxx_messageInfo_GetBuildingByIDReq.Size(m)
}
func (m *GetBuildingByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildingByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildingByIDReq proto.InternalMessageInfo

func (m *GetBuildingByIDReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetBuildingByIDResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	Building             *Building `protobuf:"bytes,2,opt,name=building,proto3" json:"building,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetBuildingByIDResp) Reset()         { *m = GetBuildingByIDResp{} }
func (m *GetBuildingByIDResp) String() string { return proto.CompactTextString(m) }
func (*GetBuildingByIDResp) ProtoMessage()    {}
func (*GetBuildingByIDResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{29}
}

func (m *GetBuildingByIDResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildingByIDResp.Unmarshal(m, b)
}
func (m *GetBuildingByIDResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildingByIDResp.Marshal(b, m, deterministic)
}
func (m *GetBuildingByIDResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildingByIDResp.Merge(m, src)
}
func (m *GetBuildingByIDResp) XXX_Size() int {
	return xxx_messageInfo_GetBuildingByIDResp.Size(m)
}
func (m *GetBuildingByIDResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildingByIDResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildingByIDResp proto.InternalMessageInfo

func (m *GetBuildingByIDResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetBuildingByIDResp) GetBuilding() *Building {
	if m != nil {
		return m.Building
	}
	return nil
}

type GetBuildingReq struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	CommunityID          int64    `protobuf:"varint,3,opt,name=communityID,proto3" json:"communityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuildingReq) Reset()         { *m = GetBuildingReq{} }
func (m *GetBuildingReq) String() string { return proto.CompactTextString(m) }
func (*GetBuildingReq) ProtoMessage()    {}
func (*GetBuildingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{30}
}

func (m *GetBuildingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildingReq.Unmarshal(m, b)
}
func (m *GetBuildingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildingReq.Marshal(b, m, deterministic)
}
func (m *GetBuildingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildingReq.Merge(m, src)
}
func (m *GetBuildingReq) XXX_Size() int {
	return xxx_messageInfo_GetBuildingReq.Size(m)
}
func (m *GetBuildingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildingReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildingReq proto.InternalMessageInfo

func (m *GetBuildingReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetBuildingReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetBuildingReq) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

type GetBuildingResp struct {
	BaseResp             *idl.Resp   `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	Buildings            []*Building `protobuf:"bytes,2,rep,name=buildings,proto3" json:"buildings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetBuildingResp) Reset()         { *m = GetBuildingResp{} }
func (m *GetBuildingResp) String() string { return proto.CompactTextString(m) }
func (*GetBuildingResp) ProtoMessage()    {}
func (*GetBuildingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{31}
}

func (m *GetBuildingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildingResp.Unmarshal(m, b)
}
func (m *GetBuildingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildingResp.Marshal(b, m, deterministic)
}
func (m *GetBuildingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildingResp.Merge(m, src)
}
func (m *GetBuildingResp) XXX_Size() int {
	return xxx_messageInfo_GetBuildingResp.Size(m)
}
func (m *GetBuildingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildingResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildingResp proto.InternalMessageInfo

func (m *GetBuildingResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetBuildingResp) GetBuildings() []*Building {
	if m != nil {
		return m.Buildings
	}
	return nil
}

type HouseCommon struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BuildingID           int64    `protobuf:"varint,2,opt,name=buildingID,proto3" json:"buildingID,omitempty"`
	Unit                 string   `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Acreage              float32  `protobuf:"fixed32,4,opt,name=acreage,proto3" json:"acreage,omitempty"`
	State                int32    `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	Rental               int32    `protobuf:"varint,6,opt,name=rental,proto3" json:"rental,omitempty"`
	OperatorID           int64    `protobuf:"varint,7,opt,name=operatorID,proto3" json:"operatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HouseCommon) Reset()         { *m = HouseCommon{} }
func (m *HouseCommon) String() string { return proto.CompactTextString(m) }
func (*HouseCommon) ProtoMessage()    {}
func (*HouseCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{32}
}

func (m *HouseCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HouseCommon.Unmarshal(m, b)
}
func (m *HouseCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HouseCommon.Marshal(b, m, deterministic)
}
func (m *HouseCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HouseCommon.Merge(m, src)
}
func (m *HouseCommon) XXX_Size() int {
	return xxx_messageInfo_HouseCommon.Size(m)
}
func (m *HouseCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_HouseCommon.DiscardUnknown(m)
}

var xxx_messageInfo_HouseCommon proto.InternalMessageInfo

func (m *HouseCommon) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HouseCommon) GetBuildingID() int64 {
	if m != nil {
		return m.BuildingID
	}
	return 0
}

func (m *HouseCommon) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *HouseCommon) GetAcreage() float32 {
	if m != nil {
		return m.Acreage
	}
	return 0
}

func (m *HouseCommon) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *HouseCommon) GetRental() int32 {
	if m != nil {
		return m.Rental
	}
	return 0
}

func (m *HouseCommon) GetOperatorID() int64 {
	if m != nil {
		return m.OperatorID
	}
	return 0
}

type House struct {
	Common               *HouseCommon `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	CreatedAt            int64        `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64        `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *House) Reset()         { *m = House{} }
func (m *House) String() string { return proto.CompactTextString(m) }
func (*House) ProtoMessage()    {}
func (*House) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{33}
}

func (m *House) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_House.Unmarshal(m, b)
}
func (m *House) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_House.Marshal(b, m, deterministic)
}
func (m *House) XXX_Merge(src proto.Message) {
	xxx_messageInfo_House.Merge(m, src)
}
func (m *House) XXX_Size() int {
	return xxx_messageInfo_House.Size(m)
}
func (m *House) XXX_DiscardUnknown() {
	xxx_messageInfo_House.DiscardUnknown(m)
}

var xxx_messageInfo_House proto.InternalMessageInfo

func (m *House) GetCommon() *HouseCommon {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *House) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *House) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type AddHouseReq struct {
	House                *HouseCommon `protobuf:"bytes,1,opt,name=house,proto3" json:"house,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddHouseReq) Reset()         { *m = AddHouseReq{} }
func (m *AddHouseReq) String() string { return proto.CompactTextString(m) }
func (*AddHouseReq) ProtoMessage()    {}
func (*AddHouseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{34}
}

func (m *AddHouseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddHouseReq.Unmarshal(m, b)
}
func (m *AddHouseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddHouseReq.Marshal(b, m, deterministic)
}
func (m *AddHouseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddHouseReq.Merge(m, src)
}
func (m *AddHouseReq) XXX_Size() int {
	return xxx_messageInfo_AddHouseReq.Size(m)
}
func (m *AddHouseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddHouseReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddHouseReq proto.InternalMessageInfo

func (m *AddHouseReq) GetHouse() *HouseCommon {
	if m != nil {
		return m.House
	}
	return nil
}

type AddHouseResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddHouseResp) Reset()         { *m = AddHouseResp{} }
func (m *AddHouseResp) String() string { return proto.CompactTextString(m) }
func (*AddHouseResp) ProtoMessage()    {}
func (*AddHouseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{35}
}

func (m *AddHouseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddHouseResp.Unmarshal(m, b)
}
func (m *AddHouseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddHouseResp.Marshal(b, m, deterministic)
}
func (m *AddHouseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddHouseResp.Merge(m, src)
}
func (m *AddHouseResp) XXX_Size() int {
	return xxx_messageInfo_AddHouseResp.Size(m)
}
func (m *AddHouseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddHouseResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddHouseResp proto.InternalMessageInfo

func (m *AddHouseResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type DelHouseReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelHouseReq) Reset()         { *m = DelHouseReq{} }
func (m *DelHouseReq) String() string { return proto.CompactTextString(m) }
func (*DelHouseReq) ProtoMessage()    {}
func (*DelHouseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{36}
}

func (m *DelHouseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelHouseReq.Unmarshal(m, b)
}
func (m *DelHouseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelHouseReq.Marshal(b, m, deterministic)
}
func (m *DelHouseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelHouseReq.Merge(m, src)
}
func (m *DelHouseReq) XXX_Size() int {
	return xxx_messageInfo_DelHouseReq.Size(m)
}
func (m *DelHouseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelHouseReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelHouseReq proto.InternalMessageInfo

func (m *DelHouseReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DelHouseResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DelHouseResp) Reset()         { *m = DelHouseResp{} }
func (m *DelHouseResp) String() string { return proto.CompactTextString(m) }
func (*DelHouseResp) ProtoMessage()    {}
func (*DelHouseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{37}
}

func (m *DelHouseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelHouseResp.Unmarshal(m, b)
}
func (m *DelHouseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelHouseResp.Marshal(b, m, deterministic)
}
func (m *DelHouseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelHouseResp.Merge(m, src)
}
func (m *DelHouseResp) XXX_Size() int {
	return xxx_messageInfo_DelHouseResp.Size(m)
}
func (m *DelHouseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelHouseResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelHouseResp proto.InternalMessageInfo

func (m *DelHouseResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetHouseByIDReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHouseByIDReq) Reset()         { *m = GetHouseByIDReq{} }
func (m *GetHouseByIDReq) String() string { return proto.CompactTextString(m) }
func (*GetHouseByIDReq) ProtoMessage()    {}
func (*GetHouseByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{38}
}

func (m *GetHouseByIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHouseByIDReq.Unmarshal(m, b)
}
func (m *GetHouseByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHouseByIDReq.Marshal(b, m, deterministic)
}
func (m *GetHouseByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHouseByIDReq.Merge(m, src)
}
func (m *GetHouseByIDReq) XXX_Size() int {
	return xxx_messageInfo_GetHouseByIDReq.Size(m)
}
func (m *GetHouseByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHouseByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetHouseByIDReq proto.InternalMessageInfo

func (m *GetHouseByIDReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetHouseByIDResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	House                *House    `protobuf:"bytes,2,opt,name=house,proto3" json:"house,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetHouseByIDResp) Reset()         { *m = GetHouseByIDResp{} }
func (m *GetHouseByIDResp) String() string { return proto.CompactTextString(m) }
func (*GetHouseByIDResp) ProtoMessage()    {}
func (*GetHouseByIDResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{39}
}

func (m *GetHouseByIDResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHouseByIDResp.Unmarshal(m, b)
}
func (m *GetHouseByIDResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHouseByIDResp.Marshal(b, m, deterministic)
}
func (m *GetHouseByIDResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHouseByIDResp.Merge(m, src)
}
func (m *GetHouseByIDResp) XXX_Size() int {
	return xxx_messageInfo_GetHouseByIDResp.Size(m)
}
func (m *GetHouseByIDResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHouseByIDResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetHouseByIDResp proto.InternalMessageInfo

func (m *GetHouseByIDResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetHouseByIDResp) GetHouse() *House {
	if m != nil {
		return m.House
	}
	return nil
}

type GetHouseReq struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	CommunityID          int64    `protobuf:"varint,3,opt,name=communityID,proto3" json:"communityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHouseReq) Reset()         { *m = GetHouseReq{} }
func (m *GetHouseReq) String() string { return proto.CompactTextString(m) }
func (*GetHouseReq) ProtoMessage()    {}
func (*GetHouseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{40}
}

func (m *GetHouseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHouseReq.Unmarshal(m, b)
}
func (m *GetHouseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHouseReq.Marshal(b, m, deterministic)
}
func (m *GetHouseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHouseReq.Merge(m, src)
}
func (m *GetHouseReq) XXX_Size() int {
	return xxx_messageInfo_GetHouseReq.Size(m)
}
func (m *GetHouseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHouseReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetHouseReq proto.InternalMessageInfo

func (m *GetHouseReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetHouseReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetHouseReq) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

type GetHouseResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	Houses               []*House  `protobuf:"bytes,2,rep,name=houses,proto3" json:"houses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetHouseResp) Reset()         { *m = GetHouseResp{} }
func (m *GetHouseResp) String() string { return proto.CompactTextString(m) }
func (*GetHouseResp) ProtoMessage()    {}
func (*GetHouseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{41}
}

func (m *GetHouseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHouseResp.Unmarshal(m, b)
}
func (m *GetHouseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHouseResp.Marshal(b, m, deterministic)
}
func (m *GetHouseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHouseResp.Merge(m, src)
}
func (m *GetHouseResp) XXX_Size() int {
	return xxx_messageInfo_GetHouseResp.Size(m)
}
func (m *GetHouseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHouseResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetHouseResp proto.InternalMessageInfo

func (m *GetHouseResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetHouseResp) GetHouses() []*House {
	if m != nil {
		return m.Houses
	}
	return nil
}

func init() {
	proto.RegisterType((*CommunityCommon)(nil), "dayan.community.srv.info.CommunityCommon")
	proto.RegisterType((*Community)(nil), "dayan.community.srv.info.Community")
	proto.RegisterType((*AddCommunityReq)(nil), "dayan.community.srv.info.AddCommunityReq")
	proto.RegisterType((*AddCommunityResp)(nil), "dayan.community.srv.info.AddCommunityResp")
	proto.RegisterType((*DelCommunityReq)(nil), "dayan.community.srv.info.DelCommunityReq")
	proto.RegisterType((*DelCommunityResp)(nil), "dayan.community.srv.info.DelCommunityResp")
	proto.RegisterType((*GetCommunityByIDReq)(nil), "dayan.community.srv.info.GetCommunityByIDReq")
	proto.RegisterType((*GetCommunityByIDResp)(nil), "dayan.community.srv.info.GetCommunityByIDResp")
	proto.RegisterType((*GetCommunityReq)(nil), "dayan.community.srv.info.GetCommunityReq")
	proto.RegisterType((*GetCommunityResp)(nil), "dayan.community.srv.info.GetCommunityResp")
	proto.RegisterType((*GetCommunityByLocReq)(nil), "dayan.community.srv.info.GetCommunityByLocReq")
	proto.RegisterType((*GetCommunityByLocResp)(nil), "dayan.community.srv.info.GetCommunityByLocResp")
	proto.RegisterType((*AssetCommon)(nil), "dayan.community.srv.info.AssetCommon")
	proto.RegisterType((*Asset)(nil), "dayan.community.srv.info.Asset")
	proto.RegisterType((*AddAssetReq)(nil), "dayan.community.srv.info.AddAssetReq")
	proto.RegisterType((*AddAssetResp)(nil), "dayan.community.srv.info.AddAssetResp")
	proto.RegisterType((*DelAssetReq)(nil), "dayan.community.srv.info.DelAssetReq")
	proto.RegisterType((*DelAssetResp)(nil), "dayan.community.srv.info.DelAssetResp")
	proto.RegisterType((*GetAssetByIDReq)(nil), "dayan.community.srv.info.GetAssetByIDReq")
	proto.RegisterType((*GetAssetByIDResp)(nil), "dayan.community.srv.info.GetAssetByIDResp")
	proto.RegisterType((*GetAssetReq)(nil), "dayan.community.srv.info.GetAssetReq")
	proto.RegisterType((*GetAssetResp)(nil), "dayan.community.srv.info.GetAssetResp")
	proto.RegisterType((*BuildingCommon)(nil), "dayan.community.srv.info.BuildingCommon")
	proto.RegisterType((*Building)(nil), "dayan.community.srv.info.Building")
	proto.RegisterType((*AddBuildingReq)(nil), "dayan.community.srv.info.AddBuildingReq")
	proto.RegisterType((*AddBuildingResp)(nil), "dayan.community.srv.info.AddBuildingResp")
	proto.RegisterType((*DelBuildingReq)(nil), "dayan.community.srv.info.DelBuildingReq")
	proto.RegisterType((*DelBuildingResp)(nil), "dayan.community.srv.info.DelBuildingResp")
	proto.RegisterType((*GetBuildingByIDReq)(nil), "dayan.community.srv.info.GetBuildingByIDReq")
	proto.RegisterType((*GetBuildingByIDResp)(nil), "dayan.community.srv.info.GetBuildingByIDResp")
	proto.RegisterType((*GetBuildingReq)(nil), "dayan.community.srv.info.GetBuildingReq")
	proto.RegisterType((*GetBuildingResp)(nil), "dayan.community.srv.info.GetBuildingResp")
	proto.RegisterType((*HouseCommon)(nil), "dayan.community.srv.info.HouseCommon")
	proto.RegisterType((*House)(nil), "dayan.community.srv.info.House")
	proto.RegisterType((*AddHouseReq)(nil), "dayan.community.srv.info.AddHouseReq")
	proto.RegisterType((*AddHouseResp)(nil), "dayan.community.srv.info.AddHouseResp")
	proto.RegisterType((*DelHouseReq)(nil), "dayan.community.srv.info.DelHouseReq")
	proto.RegisterType((*DelHouseResp)(nil), "dayan.community.srv.info.DelHouseResp")
	proto.RegisterType((*GetHouseByIDReq)(nil), "dayan.community.srv.info.GetHouseByIDReq")
	proto.RegisterType((*GetHouseByIDResp)(nil), "dayan.community.srv.info.GetHouseByIDResp")
	proto.RegisterType((*GetHouseReq)(nil), "dayan.community.srv.info.GetHouseReq")
	proto.RegisterType((*GetHouseResp)(nil), "dayan.community.srv.info.GetHouseResp")
}

func init() { proto.RegisterFile("info.proto", fileDescriptor_f140d5b28dddb141) }

var fileDescriptor_f140d5b28dddb141 = []byte{
	// 1396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x6f, 0x8b, 0xe4, 0x44,
	0x13, 0x27, 0x93, 0xcd, 0xde, 0x4c, 0xcd, 0xde, 0xec, 0x5e, 0x3f, 0xfb, 0x48, 0x08, 0x7a, 0x8e,
	0xd1, 0x3b, 0x67, 0xd5, 0x1b, 0xe1, 0x0e, 0x3d, 0x54, 0xd4, 0x9b, 0xdd, 0x81, 0x75, 0x44, 0x44,
	0x22, 0x08, 0x27, 0x0a, 0x66, 0x92, 0xde, 0xb9, 0xe0, 0x6c, 0x32, 0x9b, 0x64, 0x16, 0x16, 0x11,
	0x51, 0x7c, 0x21, 0x7e, 0xa3, 0x7b, 0x2b, 0xf8, 0x81, 0xfc, 0x06, 0xd2, 0xd5, 0xe9, 0x4e, 0x27,
	0xb3, 0x93, 0x3f, 0xc7, 0x9d, 0xef, 0xd2, 0xd5, 0x55, 0xd5, 0x55, 0xd5, 0x55, 0xbf, 0xaa, 0x0e,
	0x40, 0x10, 0x9e, 0x45, 0xe3, 0x55, 0x1c, 0xa5, 0x11, 0x31, 0x7d, 0xf7, 0xca, 0x0d, 0xc7, 0x5e,
	0x74, 0x7e, 0xbe, 0x0e, 0x83, 0xf4, 0x6a, 0x9c, 0xc4, 0x97, 0x63, 0xb6, 0x6f, 0xc1, 0xdc, 0x4d,
	0x28, 0xe7, 0xb2, 0xff, 0xd6, 0x61, 0xff, 0x44, 0xb0, 0xb0, 0x8f, 0x28, 0x24, 0x03, 0xe8, 0x04,
	0xbe, 0xa9, 0x0d, 0xb5, 0x91, 0xee, 0x74, 0x02, 0x9f, 0x10, 0xd8, 0x09, 0xdd, 0x73, 0x6a, 0x76,
	0x86, 0xda, 0xa8, 0xe7, 0xe0, 0x37, 0xb1, 0xa0, 0xbb, 0x8a, 0xa3, 0xcb, 0x20, 0xf4, 0xa8, 0xa9,
	0x23, 0x5d, 0xae, 0x19, 0xbf, 0x17, 0xa4, 0x57, 0xe6, 0x0e, 0xe7, 0x67, 0xdf, 0xe4, 0x25, 0xd8,
	0x8d, 0xe9, 0x22, 0x88, 0x42, 0xd3, 0x40, 0x6a, 0xb6, 0x62, 0xf4, 0x24, 0x8d, 0x29, 0x4d, 0xcd,
	0x5d, 0x4e, 0xe7, 0x2b, 0x62, 0xc3, 0x5e, 0x42, 0xe3, 0xc0, 0x5d, 0x7e, 0xb9, 0x3e, 0x9f, 0xd3,
	0xd8, 0xbc, 0x81, 0xbb, 0x05, 0x1a, 0x39, 0x04, 0x23, 0x8a, 0x17, 0xb3, 0xa9, 0xd9, 0x45, 0x53,
	0xf9, 0x82, 0xdc, 0x06, 0x78, 0x12, 0xad, 0x13, 0x7a, 0x12, 0xad, 0xc3, 0xd4, 0xec, 0x0d, 0xb5,
	0x91, 0xe1, 0x28, 0x14, 0xa6, 0xd9, 0x7b, 0x42, 0xbd, 0x1f, 0x67, 0x21, 0xe7, 0xe8, 0x23, 0x47,
	0x81, 0xc6, 0x78, 0xe6, 0xeb, 0x60, 0xe9, 0x07, 0xe1, 0x62, 0x12, 0x53, 0xd7, 0xdc, 0x1b, 0x6a,
	0xa3, 0x8e, 0x53, 0xa0, 0x31, 0x9e, 0x45, 0x4c, 0x69, 0x28, 0x78, 0x6e, 0x72, 0x1e, 0x95, 0x46,
	0x0e, 0x40, 0x5f, 0x46, 0x9e, 0x39, 0x18, 0xea, 0xa3, 0x8e, 0xc3, 0x3e, 0x99, 0xcd, 0x49, 0xea,
	0xa6, 0xd4, 0xdc, 0xc7, 0x63, 0xf9, 0x82, 0x0c, 0xa1, 0x9f, 0x50, 0x77, 0x49, 0xfd, 0xaf, 0x71,
	0xef, 0x00, 0xf7, 0x54, 0x12, 0xf3, 0x2a, 0x5a, 0xd1, 0xd8, 0x4d, 0xa3, 0x78, 0x36, 0x35, 0x6f,
	0xa1, 0xc3, 0x0a, 0xc5, 0xfe, 0x53, 0x83, 0x9e, 0xbc, 0x47, 0x32, 0x81, 0x5d, 0x0f, 0xef, 0x12,
	0x6f, 0xb1, 0x7f, 0xff, 0x68, 0xbc, 0x2d, 0x19, 0xc6, 0xa5, 0xcb, 0x77, 0x32, 0x41, 0xf2, 0x32,
	0xf4, 0xd6, 0x2b, 0xdf, 0x4d, 0xa9, 0x3f, 0x49, 0xf1, 0xe6, 0x75, 0x27, 0x27, 0xb0, 0x5d, 0x2f,
	0xa6, 0xd9, 0xae, 0xce, 0x77, 0x25, 0xc1, 0xfe, 0x16, 0xf6, 0x27, 0xbe, 0x2f, 0x35, 0x3b, 0xf4,
	0x82, 0x9c, 0x42, 0x4f, 0x1e, 0xde, 0xde, 0xa8, 0x5c, 0xd6, 0xfe, 0x0e, 0x0e, 0x8a, 0xba, 0x93,
	0x15, 0xb9, 0x0b, 0x5d, 0x96, 0xd2, 0xec, 0x3b, 0xd3, 0x0d, 0x63, 0xcc, 0x71, 0x46, 0x71, 0xe4,
	0x1e, 0x0b, 0xb3, 0x54, 0x34, 0x9b, 0x66, 0x5e, 0xa9, 0x24, 0xfb, 0x01, 0xec, 0x4f, 0xe9, 0xb2,
	0x60, 0x79, 0x49, 0x48, 0xdb, 0x14, 0xfa, 0x10, 0x0e, 0x8a, 0x42, 0xcd, 0x4d, 0xb2, 0x1f, 0xc2,
	0xff, 0x4e, 0x69, 0x2a, 0x65, 0x8f, 0xaf, 0x66, 0xd3, 0x66, 0x87, 0xfe, 0xaa, 0xc1, 0xe1, 0xa6,
	0x64, 0x8b, 0x60, 0x4c, 0xd4, 0x1b, 0xe9, 0x20, 0xe3, 0xeb, 0x0d, 0x6e, 0x44, 0xbd, 0x8b, 0x4f,
	0x61, 0x5f, 0x35, 0x81, 0x19, 0x7e, 0x08, 0xc6, 0x32, 0x38, 0x0f, 0x52, 0x3c, 0xda, 0x70, 0xf8,
	0x82, 0x55, 0x79, 0x74, 0x76, 0x96, 0x50, 0x9e, 0x49, 0x86, 0x93, 0xad, 0xec, 0x5f, 0xe0, 0xa0,
	0xa8, 0xa0, 0x85, 0xfd, 0x27, 0x00, 0xd2, 0x92, 0xc4, 0xec, 0x0c, 0xf5, 0xa6, 0x0e, 0x28, 0x62,
	0x76, 0x5c, 0x0e, 0xe2, 0x17, 0x91, 0xd7, 0xda, 0x0d, 0x51, 0xe6, 0x7a, 0x5e, 0xe6, 0x16, 0x74,
	0xfd, 0x20, 0x49, 0x5d, 0x06, 0x8f, 0x3b, 0x08, 0x0c, 0x72, 0x6d, 0xff, 0xae, 0xc1, 0xff, 0xaf,
	0x39, 0xf4, 0xbf, 0x76, 0xfd, 0x1f, 0x0d, 0xfa, 0x93, 0x24, 0xe1, 0x86, 0x5c, 0x83, 0xfa, 0x65,
	0x04, 0xee, 0x5c, 0x83, 0xc0, 0x16, 0x74, 0x3d, 0x37, 0xa5, 0x8b, 0x28, 0xbe, 0x42, 0x14, 0x30,
	0x1c, 0xb9, 0xce, 0x91, 0x6e, 0xa7, 0x84, 0x74, 0x6a, 0x62, 0x1b, 0x1b, 0x89, 0x2d, 0x82, 0xc9,
	0xdb, 0x81, 0xc0, 0xcc, 0x79, 0xec, 0x86, 0x7e, 0xd6, 0x04, 0xf8, 0x82, 0x75, 0x19, 0x9f, 0x26,
	0x1e, 0x82, 0x7f, 0xcf, 0xc1, 0xef, 0x12, 0x4a, 0xf6, 0x36, 0x50, 0xf2, 0x37, 0x0d, 0x0c, 0xf4,
	0x99, 0x7c, 0x5c, 0x42, 0xc8, 0x3b, 0xdb, 0xc3, 0xa7, 0x04, 0x49, 0x45, 0xc7, 0x1c, 0xff, 0x3a,
	0x25, 0xfc, 0x2b, 0x62, 0xa7, 0x5e, 0xc2, 0x4e, 0xfb, 0x73, 0xe8, 0x4f, 0x7c, 0x1f, 0xb5, 0xb2,
	0x54, 0xfb, 0x08, 0x0c, 0x97, 0x7d, 0xb7, 0x33, 0x84, 0xcb, 0xd8, 0x5f, 0xc1, 0x5e, 0xae, 0xab,
	0x45, 0x06, 0x99, 0x70, 0x03, 0x15, 0x48, 0x14, 0x14, 0x4b, 0xfb, 0x4d, 0xe8, 0x4f, 0xe9, 0x52,
	0x5a, 0xa7, 0x30, 0x6a, 0x45, 0xc6, 0xf7, 0x61, 0x2f, 0x67, 0x6c, 0x81, 0x78, 0x6f, 0x23, 0x68,
	0xa0, 0x9c, 0x40, 0xbb, 0xed, 0x87, 0x5c, 0x20, 0x40, 0x28, 0xcc, 0x2d, 0x7c, 0x7c, 0x4f, 0x04,
	0x96, 0x83, 0xdb, 0xab, 0x35, 0x81, 0x15, 0x21, 0xfd, 0x1e, 0xfa, 0xe2, 0xc8, 0xf6, 0x48, 0x50,
	0x4a, 0x6f, 0x7d, 0x13, 0xb7, 0x23, 0xd8, 0xcb, 0xd5, 0xb7, 0xf0, 0xe6, 0x21, 0xec, 0xa2, 0x7d,
	0xa2, 0xde, 0x6b, 0xdd, 0xc9, 0xd8, 0xed, 0xbf, 0x34, 0x18, 0x1c, 0x67, 0x83, 0x4b, 0x8b, 0x01,
	0xaf, 0xd6, 0x13, 0x16, 0x83, 0x15, 0x8d, 0x83, 0xc8, 0xcf, 0x2a, 0x3c, 0x5b, 0x31, 0x49, 0xba,
	0xa4, 0x97, 0xbc, 0xe4, 0x12, 0xd3, 0x18, 0xea, 0x4c, 0x52, 0x21, 0xe5, 0x25, 0x2e, 0xf1, 0xb2,
	0x58, 0xb8, 0x37, 0x36, 0x0a, 0xf7, 0x0f, 0x0d, 0xba, 0xc2, 0x09, 0xf2, 0xa8, 0x54, 0xbb, 0xa3,
	0xed, 0xa1, 0x28, 0x3a, 0xfe, 0x5c, 0xca, 0xf7, 0x1b, 0x18, 0x4c, 0x7c, 0x5f, 0x28, 0x66, 0x29,
	0x32, 0x85, 0xae, 0x98, 0x0c, 0x5b, 0x5b, 0x24, 0x25, 0xed, 0x19, 0x0e, 0x4d, 0xb9, 0xde, 0x16,
	0xb9, 0xc1, 0xef, 0xb3, 0x23, 0xee, 0xd3, 0x1e, 0xc2, 0x60, 0x4a, 0x97, 0xaa, 0x89, 0xa5, 0x1b,
	0xb7, 0x3f, 0xc0, 0x39, 0xe7, 0x59, 0x0e, 0xb3, 0xdf, 0x00, 0x72, 0x4a, 0x53, 0x21, 0x2a, 0x4a,
	0xb8, 0x7c, 0xc0, 0xcf, 0x38, 0xd7, 0x14, 0xb9, 0x5a, 0x78, 0xf4, 0x89, 0x12, 0x52, 0x5e, 0xbe,
	0x76, 0x7d, 0x48, 0x95, 0x60, 0xfe, 0x00, 0x03, 0xe5, 0xf8, 0x17, 0x51, 0xc7, 0x3f, 0x21, 0x8c,
	0x3d, 0xd3, 0x75, 0x3d, 0x82, 0x9e, 0x30, 0x54, 0x54, 0x73, 0x13, 0xef, 0x72, 0x21, 0xfb, 0xa9,
	0x06, 0xfd, 0xcf, 0xf8, 0x93, 0xe6, 0xda, 0x82, 0xbe, 0x0d, 0x20, 0x98, 0x25, 0xc2, 0x2b, 0x14,
	0x56, 0xf0, 0xec, 0x94, 0xec, 0xe5, 0x86, 0xdf, 0x08, 0xc2, 0xac, 0x06, 0x16, 0x62, 0x62, 0x11,
	0xcb, 0xbc, 0x93, 0x1b, 0x6a, 0x27, 0xc7, 0x17, 0x5d, 0x98, 0xba, 0x4b, 0x6c, 0xd5, 0x86, 0x93,
	0xad, 0x6a, 0x4b, 0x99, 0xf5, 0x60, 0xb4, 0xbd, 0x4d, 0x0f, 0x56, 0x9c, 0x7d, 0x8e, 0x3d, 0x18,
	0xb5, 0x66, 0x3d, 0x18, 0x5f, 0x88, 0xed, 0x0c, 0xe1, 0x32, 0xac, 0x11, 0xe6, 0xba, 0x78, 0x1a,
	0x1c, 0x57, 0xa4, 0x81, 0xd8, 0xb3, 0x5f, 0xc1, 0x4e, 0x2b, 0x6d, 0x28, 0x57, 0x10, 0xef, 0xaf,
	0x05, 0xb5, 0x8d, 0xea, 0xf3, 0x35, 0x4c, 0x4c, 0x94, 0xdb, 0x56, 0x9c, 0xbc, 0xab, 0x2a, 0x2c,
	0xcd, 0xad, 0x66, 0x5d, 0x95, 0x87, 0xaa, 0xb6, 0xab, 0x72, 0xd3, 0xb3, 0x20, 0xf1, 0xae, 0x2a,
	0x9d, 0x7d, 0x31, 0x5d, 0xb5, 0x75, 0xb0, 0x58, 0x57, 0x45, 0xfb, 0x1a, 0x74, 0x55, 0xae, 0x3c,
	0x63, 0xbf, 0xff, 0xf4, 0x26, 0xdc, 0x94, 0x73, 0xf5, 0x2c, 0x3c, 0x8b, 0x08, 0xc5, 0x34, 0xc8,
	0xdf, 0xe0, 0x15, 0xcf, 0xdb, 0xd2, 0xe3, 0xd8, 0x7a, 0xab, 0x29, 0x6b, 0xb2, 0x62, 0xc7, 0xa8,
	0x8f, 0xcd, 0xaa, 0x63, 0x4a, 0x2f, 0xd9, 0xaa, 0x63, 0x36, 0xde, 0xaf, 0x17, 0xc5, 0x97, 0x19,
	0x4b, 0x13, 0x72, 0x6f, 0xbb, 0xfc, 0x35, 0x6f, 0x58, 0x6b, 0xdc, 0x86, 0x9d, 0x7b, 0xa6, 0xd2,
	0xab, 0x3c, 0x2b, 0xbd, 0x3a, 0xab, 0x3c, 0xdb, 0x78, 0x5f, 0xa6, 0x70, 0x6b, 0xe3, 0xf5, 0x45,
	0x1a, 0xdb, 0xca, 0xdf, 0x87, 0xd6, 0xbb, 0xad, 0xf8, 0x93, 0x15, 0x79, 0x0c, 0x5d, 0x31, 0xa8,
	0x93, 0x3b, 0x95, 0xd7, 0x2d, 0x26, 0x4f, 0xeb, 0x6e, 0x13, 0x36, 0xae, 0x5a, 0x0c, 0xe2, 0x55,
	0xaa, 0x95, 0xa9, 0xbe, 0x4a, 0x75, 0x61, 0xa6, 0xa7, 0xf9, 0xb0, 0x8a, 0x19, 0x50, 0x7d, 0x25,
	0xea, 0x4c, 0x5f, 0x73, 0x25, 0xc5, 0x89, 0xfe, 0x31, 0x74, 0x05, 0xad, 0xca, 0x03, 0x65, 0x2c,
	0xaf, 0xf2, 0xa0, 0x30, 0x5e, 0xcf, 0x11, 0xe8, 0xe5, 0xe8, 0x38, 0xaa, 0x8c, 0xa9, 0x32, 0x2f,
	0x58, 0x47, 0x0d, 0x39, 0xf9, 0x19, 0xca, 0x30, 0x55, 0x75, 0x46, 0x71, 0x2a, 0xb3, 0x8e, 0x1a,
	0x72, 0x26, 0x2b, 0x12, 0x16, 0xc6, 0x0d, 0xbc, 0x8c, 0x77, 0x2a, 0x43, 0x50, 0x1a, 0xd0, 0xac,
	0x7b, 0x2d, 0xb8, 0xb9, 0x4f, 0x0a, 0xb9, 0xca, 0xa7, 0xe2, 0x9c, 0x65, 0x1d, 0x35, 0xe4, 0x94,
	0x35, 0xc1, 0x67, 0x81, 0xea, 0x9a, 0x10, 0x7d, 0xa3, 0xa6, 0x26, 0x72, 0xfc, 0xe7, 0x35, 0x51,
	0xab, 0x5a, 0xe9, 0xbf, 0x35, 0x35, 0x91, 0xab, 0xa6, 0x79, 0xab, 0x69, 0x50, 0x13, 0x6a, 0x1f,
	0xae, 0xa9, 0x89, 0x62, 0x3f, 0xe6, 0x35, 0x51, 0xeb, 0x81, 0xd2, 0x54, 0x6b, 0x6a, 0x42, 0x7a,
	0x30, 0xdf, 0xc5, 0x5f, 0xff, 0x0f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xfd, 0x46, 0xea,
	0x2e, 0x18, 0x00, 0x00,
}
