// Code generated by protoc-gen-go. DO NOT EDIT.
// source: info.proto

package dayan_community_srv_info

import (
	fmt "fmt"
	idl "github.com/dy-dayan/community-srv-info/idl"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddCommunityReq struct {
	Name                 string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Province             string    `protobuf:"bytes,2,opt,name=Province,proto3" json:"Province,omitempty"`
	City                 string    `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	Region               string    `protobuf:"bytes,4,opt,name=Region,proto3" json:"Region,omitempty"`
	Street               string    `protobuf:"bytes,5,opt,name=Street,proto3" json:"Street,omitempty"`
	CouncilID            int64     `protobuf:"varint,6,opt,name=CouncilID,proto3" json:"CouncilID,omitempty"`
	OrgID                int64     `protobuf:"varint,7,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	HouseCount           int32     `protobuf:"varint,8,opt,name=HouseCount,proto3" json:"HouseCount,omitempty"`
	CheckInCount         int32     `protobuf:"varint,9,opt,name=CheckInCount,proto3" json:"CheckInCount,omitempty"`
	BuildingArea         int32     `protobuf:"varint,10,opt,name=BuildingArea,proto3" json:"BuildingArea,omitempty"`
	GreeningArea         int32     `protobuf:"varint,11,opt,name=GreeningArea,proto3" json:"GreeningArea,omitempty"`
	Loc                  []float32 `protobuf:"fixed32,12,rep,packed,name=Loc,proto3" json:"Loc,omitempty"`
	State                int32     `protobuf:"varint,13,opt,name=State,proto3" json:"State,omitempty"`
	OperatorID           int64     `protobuf:"varint,14,opt,name=OperatorID,proto3" json:"OperatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddCommunityReq) Reset()         { *m = AddCommunityReq{} }
func (m *AddCommunityReq) String() string { return proto.CompactTextString(m) }
func (*AddCommunityReq) ProtoMessage()    {}
func (*AddCommunityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{0}
}

func (m *AddCommunityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommunityReq.Unmarshal(m, b)
}
func (m *AddCommunityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommunityReq.Marshal(b, m, deterministic)
}
func (m *AddCommunityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommunityReq.Merge(m, src)
}
func (m *AddCommunityReq) XXX_Size() int {
	return xxx_messageInfo_AddCommunityReq.Size(m)
}
func (m *AddCommunityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommunityReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommunityReq proto.InternalMessageInfo

func (m *AddCommunityReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddCommunityReq) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *AddCommunityReq) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *AddCommunityReq) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *AddCommunityReq) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *AddCommunityReq) GetCouncilID() int64 {
	if m != nil {
		return m.CouncilID
	}
	return 0
}

func (m *AddCommunityReq) GetOrgID() int64 {
	if m != nil {
		return m.OrgID
	}
	return 0
}

func (m *AddCommunityReq) GetHouseCount() int32 {
	if m != nil {
		return m.HouseCount
	}
	return 0
}

func (m *AddCommunityReq) GetCheckInCount() int32 {
	if m != nil {
		return m.CheckInCount
	}
	return 0
}

func (m *AddCommunityReq) GetBuildingArea() int32 {
	if m != nil {
		return m.BuildingArea
	}
	return 0
}

func (m *AddCommunityReq) GetGreeningArea() int32 {
	if m != nil {
		return m.GreeningArea
	}
	return 0
}

func (m *AddCommunityReq) GetLoc() []float32 {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *AddCommunityReq) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *AddCommunityReq) GetOperatorID() int64 {
	if m != nil {
		return m.OperatorID
	}
	return 0
}

type AddCommunityResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	CommunityID          int64     `protobuf:"varint,2,opt,name=CommunityID,proto3" json:"CommunityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddCommunityResp) Reset()         { *m = AddCommunityResp{} }
func (m *AddCommunityResp) String() string { return proto.CompactTextString(m) }
func (*AddCommunityResp) ProtoMessage()    {}
func (*AddCommunityResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{1}
}

func (m *AddCommunityResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommunityResp.Unmarshal(m, b)
}
func (m *AddCommunityResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommunityResp.Marshal(b, m, deterministic)
}
func (m *AddCommunityResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommunityResp.Merge(m, src)
}
func (m *AddCommunityResp) XXX_Size() int {
	return xxx_messageInfo_AddCommunityResp.Size(m)
}
func (m *AddCommunityResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommunityResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommunityResp proto.InternalMessageInfo

func (m *AddCommunityResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *AddCommunityResp) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

type DelCommunityReq struct {
	CommunityID          int64    `protobuf:"varint,1,opt,name=CommunityID,proto3" json:"CommunityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelCommunityReq) Reset()         { *m = DelCommunityReq{} }
func (m *DelCommunityReq) String() string { return proto.CompactTextString(m) }
func (*DelCommunityReq) ProtoMessage()    {}
func (*DelCommunityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{2}
}

func (m *DelCommunityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCommunityReq.Unmarshal(m, b)
}
func (m *DelCommunityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCommunityReq.Marshal(b, m, deterministic)
}
func (m *DelCommunityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCommunityReq.Merge(m, src)
}
func (m *DelCommunityReq) XXX_Size() int {
	return xxx_messageInfo_DelCommunityReq.Size(m)
}
func (m *DelCommunityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCommunityReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelCommunityReq proto.InternalMessageInfo

func (m *DelCommunityReq) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

type DelCommunityResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DelCommunityResp) Reset()         { *m = DelCommunityResp{} }
func (m *DelCommunityResp) String() string { return proto.CompactTextString(m) }
func (*DelCommunityResp) ProtoMessage()    {}
func (*DelCommunityResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{3}
}

func (m *DelCommunityResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCommunityResp.Unmarshal(m, b)
}
func (m *DelCommunityResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCommunityResp.Marshal(b, m, deterministic)
}
func (m *DelCommunityResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCommunityResp.Merge(m, src)
}
func (m *DelCommunityResp) XXX_Size() int {
	return xxx_messageInfo_DelCommunityResp.Size(m)
}
func (m *DelCommunityResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCommunityResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelCommunityResp proto.InternalMessageInfo

func (m *DelCommunityResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetCommunityReq struct {
	CommunityID          int64    `protobuf:"varint,1,opt,name=CommunityID,proto3" json:"CommunityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommunityReq) Reset()         { *m = GetCommunityReq{} }
func (m *GetCommunityReq) String() string { return proto.CompactTextString(m) }
func (*GetCommunityReq) ProtoMessage()    {}
func (*GetCommunityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{4}
}

func (m *GetCommunityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommunityReq.Unmarshal(m, b)
}
func (m *GetCommunityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommunityReq.Marshal(b, m, deterministic)
}
func (m *GetCommunityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommunityReq.Merge(m, src)
}
func (m *GetCommunityReq) XXX_Size() int {
	return xxx_messageInfo_GetCommunityReq.Size(m)
}
func (m *GetCommunityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommunityReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommunityReq proto.InternalMessageInfo

func (m *GetCommunityReq) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

type GetCommunityResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Province             string    `protobuf:"bytes,3,opt,name=Province,proto3" json:"Province,omitempty"`
	City                 string    `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	Region               string    `protobuf:"bytes,5,opt,name=Region,proto3" json:"Region,omitempty"`
	Street               string    `protobuf:"bytes,6,opt,name=Street,proto3" json:"Street,omitempty"`
	CouncilID            int64     `protobuf:"varint,7,opt,name=CouncilID,proto3" json:"CouncilID,omitempty"`
	OrgID                int64     `protobuf:"varint,8,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	HouseCount           int32     `protobuf:"varint,9,opt,name=HouseCount,proto3" json:"HouseCount,omitempty"`
	CheckInCount         int32     `protobuf:"varint,10,opt,name=CheckInCount,proto3" json:"CheckInCount,omitempty"`
	BuildingArea         int32     `protobuf:"varint,11,opt,name=BuildingArea,proto3" json:"BuildingArea,omitempty"`
	GreeningArea         int32     `protobuf:"varint,12,opt,name=GreeningArea,proto3" json:"GreeningArea,omitempty"`
	Loc                  []float32 `protobuf:"fixed32,13,rep,packed,name=Loc,proto3" json:"Loc,omitempty"`
	State                int32     `protobuf:"varint,14,opt,name=State,proto3" json:"State,omitempty"`
	OperatorID           int64     `protobuf:"varint,15,opt,name=OperatorID,proto3" json:"OperatorID,omitempty"`
	CreatedAt            int64     `protobuf:"varint,16,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            int64     `protobuf:"varint,17,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCommunityResp) Reset()         { *m = GetCommunityResp{} }
func (m *GetCommunityResp) String() string { return proto.CompactTextString(m) }
func (*GetCommunityResp) ProtoMessage()    {}
func (*GetCommunityResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{5}
}

func (m *GetCommunityResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommunityResp.Unmarshal(m, b)
}
func (m *GetCommunityResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommunityResp.Marshal(b, m, deterministic)
}
func (m *GetCommunityResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommunityResp.Merge(m, src)
}
func (m *GetCommunityResp) XXX_Size() int {
	return xxx_messageInfo_GetCommunityResp.Size(m)
}
func (m *GetCommunityResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommunityResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommunityResp proto.InternalMessageInfo

func (m *GetCommunityResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetCommunityResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetCommunityResp) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *GetCommunityResp) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *GetCommunityResp) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *GetCommunityResp) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *GetCommunityResp) GetCouncilID() int64 {
	if m != nil {
		return m.CouncilID
	}
	return 0
}

func (m *GetCommunityResp) GetOrgID() int64 {
	if m != nil {
		return m.OrgID
	}
	return 0
}

func (m *GetCommunityResp) GetHouseCount() int32 {
	if m != nil {
		return m.HouseCount
	}
	return 0
}

func (m *GetCommunityResp) GetCheckInCount() int32 {
	if m != nil {
		return m.CheckInCount
	}
	return 0
}

func (m *GetCommunityResp) GetBuildingArea() int32 {
	if m != nil {
		return m.BuildingArea
	}
	return 0
}

func (m *GetCommunityResp) GetGreeningArea() int32 {
	if m != nil {
		return m.GreeningArea
	}
	return 0
}

func (m *GetCommunityResp) GetLoc() []float32 {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *GetCommunityResp) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *GetCommunityResp) GetOperatorID() int64 {
	if m != nil {
		return m.OperatorID
	}
	return 0
}

func (m *GetCommunityResp) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *GetCommunityResp) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*AddCommunityReq)(nil), "dayan.community.srv.info.AddCommunityReq")
	proto.RegisterType((*AddCommunityResp)(nil), "dayan.community.srv.info.AddCommunityResp")
	proto.RegisterType((*DelCommunityReq)(nil), "dayan.community.srv.info.DelCommunityReq")
	proto.RegisterType((*DelCommunityResp)(nil), "dayan.community.srv.info.DelCommunityResp")
	proto.RegisterType((*GetCommunityReq)(nil), "dayan.community.srv.info.GetCommunityReq")
	proto.RegisterType((*GetCommunityResp)(nil), "dayan.community.srv.info.GetCommunityResp")
}

func init() { proto.RegisterFile("info.proto", fileDescriptor_f140d5b28dddb141) }

var fileDescriptor_f140d5b28dddb141 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0x86, 0x65, 0x0c, 0x04, 0x06, 0x13, 0xdc, 0x55, 0x55, 0xad, 0x50, 0x55, 0x59, 0x1c, 0x2a,
	0xda, 0x83, 0x0f, 0xc9, 0xad, 0x37, 0x82, 0xa5, 0xd4, 0x52, 0xd5, 0x54, 0x8e, 0x7a, 0xeb, 0xc5,
	0xb1, 0x27, 0xd4, 0x2a, 0xec, 0xba, 0xeb, 0x25, 0x12, 0x0f, 0xd1, 0xb7, 0xea, 0x13, 0xf5, 0x09,
	0xaa, 0xdd, 0x05, 0x62, 0x3b, 0x31, 0x81, 0xdb, 0xce, 0x3f, 0xff, 0x68, 0xec, 0x9d, 0x6f, 0x16,
	0x20, 0x63, 0xf7, 0xdc, 0xcf, 0x05, 0x97, 0x9c, 0xd0, 0x34, 0xde, 0xc4, 0xcc, 0x4f, 0xf8, 0x6a,
	0xb5, 0x66, 0x99, 0xdc, 0xf8, 0x85, 0x78, 0xf0, 0x55, 0x7e, 0x0c, 0x77, 0x71, 0x81, 0xc6, 0x35,
	0xf9, 0x63, 0xc3, 0x68, 0x96, 0xa6, 0xf3, 0x9d, 0x2b, 0xc2, 0xdf, 0x84, 0x40, 0xfb, 0x6b, 0xbc,
	0x42, 0x6a, 0x79, 0xd6, 0xb4, 0x1f, 0xe9, 0x33, 0x19, 0x43, 0xef, 0x9b, 0xe0, 0x0f, 0x19, 0x4b,
	0x90, 0xb6, 0xb4, 0xbe, 0x8f, 0x95, 0x7f, 0x9e, 0xc9, 0x0d, 0xb5, 0x8d, 0x5f, 0x9d, 0xc9, 0x1b,
	0xe8, 0x46, 0xb8, 0xc8, 0x38, 0xa3, 0x6d, 0xad, 0x6e, 0x23, 0xa5, 0xdf, 0x4a, 0x81, 0x28, 0x69,
	0xc7, 0xe8, 0x26, 0x22, 0x6f, 0xa1, 0x3f, 0xe7, 0x6b, 0x96, 0x64, 0xcb, 0x30, 0xa0, 0x5d, 0xcf,
	0x9a, 0xda, 0xd1, 0xa3, 0x40, 0x5e, 0x43, 0xe7, 0x46, 0x2c, 0xc2, 0x80, 0x9e, 0xe9, 0x8c, 0x09,
	0xc8, 0x3b, 0x80, 0xcf, 0x7c, 0x5d, 0xa0, 0xf2, 0x49, 0xda, 0xf3, 0xac, 0x69, 0x27, 0x2a, 0x29,
	0x64, 0x02, 0xce, 0xfc, 0x27, 0x26, 0xbf, 0x42, 0x66, 0x1c, 0x7d, 0xed, 0xa8, 0x68, 0xca, 0x73,
	0xb5, 0xce, 0x96, 0x69, 0xc6, 0x16, 0x33, 0x81, 0x31, 0x05, 0xe3, 0x29, 0x6b, 0xca, 0x73, 0x2d,
	0x10, 0xd9, 0xce, 0x33, 0x30, 0x9e, 0xb2, 0x46, 0x5c, 0xb0, 0xbf, 0xf0, 0x84, 0x3a, 0x9e, 0x3d,
	0x6d, 0x45, 0xea, 0xa8, 0xbe, 0xf9, 0x56, 0xc6, 0x12, 0xe9, 0x50, 0xdb, 0x4d, 0xa0, 0xbe, 0xf9,
	0x26, 0x47, 0x11, 0x4b, 0x2e, 0xc2, 0x80, 0x9e, 0xeb, 0xdf, 0x29, 0x29, 0x93, 0x1f, 0xe0, 0x56,
	0xc7, 0x51, 0xe4, 0xe4, 0x3d, 0xf4, 0xae, 0xe2, 0x02, 0xd5, 0x59, 0xcf, 0x64, 0x70, 0x01, 0xbe,
	0x1e, 0xa1, 0x52, 0xa2, 0x7d, 0x8e, 0x78, 0x30, 0xd8, 0x17, 0x86, 0x81, 0x1e, 0x93, 0x1d, 0x95,
	0xa5, 0xc9, 0x25, 0x8c, 0x02, 0x5c, 0x56, 0x86, 0x5d, 0x2b, 0xb2, 0x9e, 0x16, 0x7d, 0x02, 0xb7,
	0x5a, 0x74, 0xfc, 0x27, 0xa9, 0x86, 0xd7, 0x28, 0x4f, 0x6c, 0xf8, 0xcf, 0x06, 0xb7, 0x5a, 0x75,
	0xc2, 0x25, 0xec, 0xe0, 0x6d, 0x35, 0xc0, 0x6b, 0x37, 0xc0, 0xdb, 0x7e, 0x16, 0xde, 0x4e, 0x03,
	0xbc, 0xdd, 0x66, 0x78, 0xcf, 0x1a, 0xe1, 0xed, 0x35, 0xc3, 0xdb, 0x7f, 0x11, 0x5e, 0x38, 0x02,
	0xde, 0xc1, 0x11, 0xf0, 0x3a, 0xcd, 0xf0, 0x0e, 0x9f, 0x81, 0xf7, 0xbc, 0x19, 0xde, 0x51, 0x1d,
	0x5e, 0x7d, 0x0f, 0x02, 0x63, 0x89, 0xe9, 0x4c, 0x52, 0x77, 0x7b, 0x0f, 0x3b, 0x41, 0x65, 0xbf,
	0xe7, 0xe9, 0x36, 0xfb, 0xca, 0x64, 0xf7, 0xc2, 0xc5, 0xdf, 0x16, 0x0c, 0x1f, 0x21, 0x60, 0xf7,
	0x9c, 0x20, 0x38, 0xe5, 0x55, 0x20, 0x1f, 0xfc, 0xa6, 0x17, 0xcd, 0xaf, 0xbd, 0x60, 0xe3, 0x8f,
	0xc7, 0x5a, 0x8b, 0x5c, 0xb5, 0x29, 0xe3, 0x7d, 0xa8, 0x4d, 0x6d, 0x77, 0x0e, 0xb5, 0x79, 0xb2,
	0x31, 0x08, 0x4e, 0x99, 0xe9, 0x43, 0x6d, 0x6a, 0x1b, 0x73, 0xa8, 0x4d, 0x7d, 0x4d, 0xee, 0xba,
	0xfa, 0x59, 0xbf, 0xfc, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x68, 0x12, 0x27, 0x0b, 0x0a, 0x06, 0x00,
	0x00,
}
